### ISSUE TITLE
[Lilac] Autofocus getting stuck in a certain range

### ISSUE THREAD

**Issue by djselbeck** [sonyxperiadev/bug_tracker#143]
**Platform:** 
Yoshino
**Device:** 
Lilac
**Kernel version:** 
4.4.138-gc1cbe0d01eb7-dirty
**Android version:** 
8.1.0 (July patch)
**Description**
The autofocus can get stuck in a certain focus range unable to focus on near or far objects until the camera application is restarted. It happens more often in landscape mode.

**Symptoms**
Pictures are out of focus

**How to reproduce**
Use camera in landscape mode and try to alternate between far, near and middle far objects.

I've made a small video demonstrating the problem:

https://www.youtube.com/watch?v=OIgOnNwHCZQ

You can see that the autofocus works for some time at the beginning but gets stuck after a few focus operations and is neither correctly focusing on far nor on near objects.

(Please excuse the video resolution as my screen cam only records in this resolution)

**Comment by jamuir** [comment]
I also experience focus issues on maple (XZP).

Thanks for reporting this.

**Comment by jerpelea** [comment]
It should be fixed now 
please retest with the latest code

**Comment by djselbeck** [comment]
Sorry for the delay (was on vacation). I can still reproduce the issue with 8.1_r35 rebuild just now and the newest OEM image

**Comment by djselbeck** [comment]
Seems to still appear with continuous autofocus with AOSP camera and OpenCamera.

However if I use AutoFocus in OpenCamera it will not get stuck, sometimes miss focus but still recovers after another try

**Comment by jerpelea** [comment]
The lens behaves normal now and there will be an improvement on the focus quality after the CASH calibration will be merged.
