### ISSUE TITLE
[tama] - Android 9.0r16 - android.com.phone died

### ISSUE THREAD

**Issue by hellobbn** [sonyxperiadev/bug_tracker#235]
**Platform:**   Tama
**Device:** akari (H8296)
**Kernel version:** 4.9.103
**Android version:** 9

**Description**
When system boots, two card show up but the phone shows no signal. After some time, the phone automatically restarts. But the phone doesn't crash when I turn on the airplane mode.

**Symptoms**
```
11-12 17:47:25.142  1347  3033 W ActivityManager: Re-adding persistent process ProcessRecord{f280764 3855:com.android.phone/1001}
11-12 17:47:25.166  1347  1406 I ActivityManager: Start proc 3924:com.android.phone/1001 for restart com.android.phone
11-12 17:47:25.446  3924  3924 I ImsResolver: Adding newly added ImsService to cache: ComponentInfo{com.android.phone/com.android.internal.telephony.ims.ImsResolver}
11-12 17:47:25.447  3924  3924 I ImsResolver: Binding ImsService: ComponentInfo{com.android.phone/com.android.internal.telephony.ims.ImsResolver} with features: [{s=0, f=0}, {s=1, f=1}, {s=0, f=1}, {s=1, f=0}]
11-12 17:47:25.447  3924  3924 I ImsServiceController: Granting Runtime permissions to:ComponentInfo{com.android.phone/com.android.internal.telephony.ims.ImsResolver}
11-12 17:47:25.448  3924  3924 I ImsServiceController: Binding ImsService:ComponentInfo{com.android.phone/com.android.internal.telephony.ims.ImsResolver}
11-12 17:47:25.539  3924  3924 D CarrierConfigLoader: mHandler: 12 phoneId: 0
11-12 17:47:25.542  3924  3924 W PhoneGlobals: Can't get phone with sub id = -1
11-12 17:47:25.549  1347  3923 I Telecom : PhoneAccountRegistrar: Modify account: [ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, ***, UserHandle{0}]: TSI.rPA@AKQ
11-12 17:47:25.550  3924  3924 I TelecomFramework: AccountEntry: Registered phoneAccount: [[ ] PhoneAccount: ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, ***, UserHandle{0} Capabilities: CallProvider MultiUser PlaceEmerg SimSub  Audio Routes: BESW Schemes: tel voicemail  Extras: Bundle[{android.telecom.extra.SUPPORTS_VIDEO_CALLING_FALLBACK=true}] GroupId: ***] with handle: ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, ***, UserHandle{0}
11-12 17:47:25.552  3924  3924 I TelecomFramework: : Carrier-config changed, checking for phone account updates.
11-12 17:47:25.557  3924  3924 E AndroidRuntime: Process: com.android.phone, PID: 3924
11-12 17:47:25.558  1347  3923 W ActivityManager: Process com.android.phone has crashed too many times: killing!
11-12 17:47:25.593   576   576 I ServiceManager: service 'iphonesubinfo' died
11-12 17:47:25.593   576   576 I ServiceManager: service 'phone' died
11-12 17:47:25.593   576   576 I ServiceManager: service 'simphonebook' died
11-12 17:47:25.594  1347  1401 I ActivityManager: Process com.android.phone (pid 3924) has died: pers PER
11-12 17:47:25.595  1347  1401 W ActivityManager: Scheduling restart of crashed service com.android.phone/.TelephonyDebugService in 0ms
```

**How to reproduce**
Flash the phone according to the instructions by Sony.

**Comment by jerpelea** [comment]
the issue is fixed in vendor v3 and will be released soon

**Comment by hellobbn** [comment]
Still have the same problem with vendor v3. The `dmesg` shows:
```
[  251.864852] Fatal error on the modem.
[  251.865165] modem subsystem failure reason: dog_hb.c:256:Task starvation: ps, ping: 4, triage with owner(d.dump 0x4a83fd80).
[  251.865864] subsys-restart: subsystem_restart_dev(): Restart sequence requested for modem, restart_level = SYSTEM.
```
