### ISSUE TITLE
[lilac] device doesn't wake up from sleep

### ISSUE THREAD

**Issue by VictorRyabov** [sonyxperiadev/bug_tracker#257]
**Platform:** yoshio
**Device:** lilac
**Kernel version:** 4.9
**Android version:** 9
**OEM version:**v3,4

**Description**
my lilac doesn't wake up from deep sleep
(I have to use 3 buttons to turn off and and on again). If the music player is playing smth keeping the device awake all works fine. Can anyone please confirm this issue? 

**Symptoms**
Device won't wake up from sleep using power button or any other way. 

**How to reproduce**
Install aosp with latest oem, leave in sleep for 3 to 20 minutes (may vary)

**Comment by bartcubbins** [comment]
The same on maple

**Comment by VictorRyabov** [comment]
@jerpelea Here are 2 logcats from working device into deep sleep(not responding to anything). Please, have a look. I hope this helps to resolve the issuu. Thank you!
[logs_lilac.zip](https://github.com/sonyxperiadev/bug_tracker/files/2681148/logs_lilac.zip)

**Comment by VictorRyabov** [comment]
@jerpelea just checking if the logs are any good for you to address the issue or should I take new ones?

**Comment by jerpelea** [comment]
please wait for v4

**Comment by VictorRyabov** [comment]
> please wait for v4

unfortunately, the issue persists on freshly built aosp with oem v4

**Comment by sjllls** [comment]
Please rebuild , this issue has been solved on poplar, build with prebuild kernel on 2019.1.5.
OEM v4

**Comment by djselbeck** [comment]
Nothing changed for Yoshino/Lilac (rebuild just now, oem v4) self-built kernel

**Comment by papjul** [comment]
According to other users below, maple and poplar were affected, so all yoshino platform, not just lilac.
@sjllls is using a prebuilt kernel (I don't know where you can find it?) instead of self built so maybe there is a fix in the prebuilt kernel that was not committed in the kernel tree that we build?

**Comment by russel5** [comment]
This guy @sjllls few days ago wrote that he have working camera on poplar. For lilac camera not working at right time.
Today he open a new thread where posted that camera not working on poplar. And im not think that prebuild kernel fix this issue. And im not trust this person.

**Comment by sjllls** [comment]
> This guy @sjllls few days ago wrote that he have working camera on poplar. For lilac camera not working at right time.
> Today he open a new thread where posted that camera not working on poplar. And im not think that prebuild kernel fix this issue. And im not trust this person.

Nothing need to say, just see this video. Camera donesn't work on poplar ?
https://youtu.be/oxvPGbAMTos

**Comment by sjllls** [comment]
XZ1 run AOSP I  built on 2019.1.4 for 5 hours , no sleep dead.
It's run with a prebuild kernel.
Do you still believe in  poplar own the same bugs as lilac?
Video uploaded: https://youtu.be/TGuzAsTtZ5E

@russel5 @djselbeck @VictorRyabov @papjul

**Comment by jerpelea** [comment]
can you both post the sw version showb by 
fastboot getvar all

thanks

**Comment by jerpelea** [comment]
@sjllls @VictorRyabov

**Comment by VictorRyabov** [comment]
I'm sorry I can't post output as I've moved to stock because of this bug. Maybe @djselbeck can post it for you.

**Comment by djselbeck** [comment]
Sorry I only have the XZ1c (lilac) and also not reachable at the moment.

**Comment by russel5** [comment]
@jerpelea what is your SW?
i not sure for 100% but im think that im using new fw 47.2.A.0.306

**Comment by sjllls** [comment]
> can you both post the sw version showb by
> fastboot getvar all
> 
> thanks

(bootloader) unlocked:yes
(bootloader) off-mode-charge:0
(bootloader) charger-screen-enabled:0
(bootloader) battery-soc-ok:yes
(bootloader) battery-voltage:4026
(bootloader) version-baseband:1307-7511_47.1.A.12.270
(bootloader) version-bootloader:1306-5035_X_Boot_MSM8998_LA1.1_O_82
(bootloader) variant:MSM UFS
(bootloader) partition-type:cache:ext4
(bootloader) partition-size:cache: 0x17C00000
(bootloader) partition-type:userdata:ext4
(bootloader) partition-size:userdata: 0xCFA976000
(bootloader) partition-type:system:ext4
(bootloader) partition-size:system: 0x138800000
(bootloader) secure:no
(bootloader) serialno:BH903JYK8Z
(bootloader) serial:f7b358fe
(bootloader) product:G8342
(bootloader) max-download-size:536870912
(bootloader) kernel:uefi
all: 
finished. total time: 0.002s

@jerpelea

**Comment by djselbeck** [comment]
For what its worth, here are the values for my lilac (XZ1c):

> $ fastboot getvar all
(bootloader) hw-revision:20001
(bootloader) unlocked:yes
(bootloader) off-mode-charge:0
(bootloader) charger-screen-enabled:0
(bootloader) battery-soc-ok:yes
(bootloader) battery-voltage:4308
(bootloader) version-baseband:1307-7511_47.1.A.12.270
(bootloader) version-bootloader:1306-5035_X_Boot_MSM8998_LA2.0_P_104
(bootloader) erase-block-size: 0x1000
(bootloader) logical-block-size: 0x1000
(bootloader) variant:MSM UFS
...
(bootloader) secure:no
(bootloader) serialno:xxxxxx
(bootloader) serial:xxxxxx
(bootloader) product:G8441
(bootloader) max-download-size:536870912
(bootloader) kernel:uefi

**Comment by jerpelea** [comment]
@djselbeck  interesting. you are on 47.1.A.12.270 with the new BL while I am on 47.1.A.16.20
with an old BL LA1.1_O_82

Can you please try the old SW

**Comment by djselbeck** [comment]
Yes, I can try if it is safe do downgrade (and if I can find a laptop with windows on it at work :-D )

**Comment by jerpelea** [comment]
:) thanks

**Comment by djselbeck** [comment]
The issue still exists. My device (lilac) is not waking up at the moment

**Comment by jerpelea** [comment]
Thanks for the clarification 
now that we have the same base it is easyer

**Comment by oshmoun** [comment]
https://github.com/sonyxperiadev/kernel/pull/1880
would be great if anybody would test this on yoshino

**Comment by djselbeck** [comment]
Lilac with this applied looks promising so far. I report back later after more testing

**Comment by djselbeck** [comment]
Unfortunately it still freezes

**Comment by oshmoun** [comment]
@djselbeck thanks! so need to switch wakegpio as well, will update the pr

**Comment by stefanhh0** [comment]
I am using lilac as well and as a workaround I've installed a wakelock tool that prevents the cpu from falling into deep sleep.

**Comment by oshmoun** [comment]
please try again now that a possible fix has been merged
https://github.com/sonyxperiadev/kernel/pull/1884

**Comment by kholk** [comment]
The issue has been resolved with https://github.com/sonyxperiadev/kernel/pull/1884

This can closed. Thanks everyone for reporting and testing the various proposed solutions.

**Comment by djselbeck** [comment]
My lilac device will still freeze ti death with the patch applied. But after trying to power on the device it is not reacting but rebooting after a few seconds

**Comment by jerpelea** [comment]
please flash fhe latest 47.1.a.x.x SW with flashtool, boot the device with a SIM then flash AOSP

Thanks

**Comment by djselbeck** [comment]
Okay, thanks. I am installing 47.1.A.16.20 Customized_NOBA now. Reporting back after reflash with AOSP and everything. Thanks for all your hard work.

**Comment by djselbeck** [comment]
Works more stable for now. No freeze on device wake up anymore. One freeze and reboot after AOSP flash for now but seems to be unrelated to this issue. So it seems to be fixed now.

**Comment by kholk** [comment]
Great to hear that!
