### ISSUE TITLE
[tone], [yoshino] No in-call audio when connected to bluetooth headset

### ISSUE THREAD

**Issue by ix5** [sonyxperiadev/bug_tracker#263]
**Platform:** tone
**Device:** kagura
**Kernel version:** 4.9
**Android version:** 9

**Description**
When there is a bluetooth headset connected with default settings, there is no in-call audio. Going into the bluetooth device settings and deselecting "Call audio" for the connected device makes in-call audio work again.
Someone suspected it might be faulty acdb mappings.

**Symptoms**
```
# When calling
Device: [00:18:09:C4:8A:8C], supportedBluetoothDevices: [00:18:09:C4:8A:8C]] -> [AudioState isMuted: false, route: BLUETOOTH, supportedRouteMask: EARPIECE, BLUETOOTH, SPEAKER, activeBluetoothDevice: [00:18:09:C4:8A:8C], supportedBluetoothDevices: [00:18:09:C4:8A:8C]]: (...->CS.crCo->H.CS.crCo->H.CS.crCo.pICR)->CSW.hCCC->CARSM.pM_UPDATE_SYSTEM_AUDIO_ROUTE@E-E-AKU
12-12 21:45:00.885  1096  2543 I Telecom : InCallController: Sending updateCall [TC@1, DIALING, com.android.phone/com.android.services.telephony.TelephonyConnectionService, tel:****, A, childs(0), has_parent(false), [Capabilities: CAPABILITY_SUPPORT_HOLD CAPABILITY_MUTE CAPABILITY_CANNOT_DOWNGRADE_VIDEO_TO_AUDIO], [Properties:]]: CSW.sSH@AKg
12-12 21:45:00.899     0     0 E qdsp_cvp_callback: cmd = 0x13199 returned error = 0x2
12-12 21:45:00.900  1096  2543 I Telecom : InCallController: Components updated: [ComponentInfo{com.android.dialer/com.android.incallui.InCallServiceImpl}, ComponentInfo{com.sony.transmitpower/com.sony.transmitpower.service.InCallObserverService}]: CSW.sSH@AKg
12-12 21:45:00.901     0     0 E voice_send_cvp_device_channels_cmd: DSP returned error[ADSP_EBADPARAM]
12-12 21:45:00.900  1096  2543 I Telecom : InCallController: Sending updateCall [TC@1, DIALING, com.android.phone/com.android.services.telephony.TelephonyConnectionService, tel:****, A, childs(0), has_parent(false), [Capabilities: CAPABILITY_SUPPORT_HOLD CAPABILITY_MUTE CAPABILITY_CANNOT_DOWNGRADE_VIDEO_TO_AUDIO], [Properties:]]: CSW.sCDN@AKk
12-12 21:45:00.901     0     0 E voice_send_cvp_media_fmt_info_cmd: Set channel info failed err: -22
12-12 21:45:00.901     0     0 E voice_setup_vocproc: Set media format info failed err:-22
12-12 21:45:00.901     0     0 E         : setup voice failed
12-12 21:45:00.913  1096  2543 I Telecom : InCallController: Components updated: [ComponentInfo{com.android.dialer/com.android.incallui.InCallServiceImpl}, ComponentInfo{com.sony.transmitpower/com.sony.transmitpower.service.InCallObserverService}]: CSW.sCDN@AKk

# When enabling phone calls in bt headset settings
12-12 21:49:33.017   611   729 I hash_map_utils: key: '00:18:09:C4:8A:8C' value: ''
12-12 21:49:33.018   591  6902 W DeviceHAL: Error from HAL Device in function open_input_stream: Invalid argument
12-12 21:49:33.021   611  7547 I AudioFlinger: AudioFlinger's thread 0xe2c0e300 tid=7547 ready to run
12-12 21:49:33.026   591  6902 W DeviceHAL: Error from HAL Device in function open_input_stream: Invalid argument
12-12 21:49:33.034   611  7548 I AudioFlinger: AudioFlinger's thread 0xe2983a00 tid=7548 ready to run
12-12 21:49:33.039  7354  7397 W HeadsetStateMachine: processVendorSpecificAt: command type error in +APLSIRI?
```

These are at bootup
```
03-04 09:59:35.834   554   692 E Diag_Lib:  Diag_LSM_Init: Failed to open handle to diag driver, error = 13
03-04 09:59:35.859   554   692 D         : Failed to fetch the lookup information of the device 0000001A 
03-04 09:59:35.859   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.859   554   692 D         : Failed to fetch the lookup information of the device 0000001A 
03-04 09:59:35.860   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.860   554   692 D         : Failed to fetch the lookup information of the device 0000001A 
03-04 09:59:35.861   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.861   554   692 D         : Failed to fetch the lookup information of the device 0000001B 
03-04 09:59:35.861   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.863   554   692 D         : Failed to fetch the lookup information of the device 0000001B 
03-04 09:59:35.863   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.864   554   692 D         : Failed to fetch the lookup information of the device 0000001B 
03-04 09:59:35.864   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.865   554   692 D         : Failed to fetch the lookup information of the device 0000001C 
03-04 09:59:35.866   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.866   554   692 D         : Failed to fetch the lookup information of the device 0000001C 
03-04 09:59:35.867   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.867   554   692 D         : Failed to fetch the lookup information of the device 0000001C 
03-04 09:59:35.868   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.868   554   692 D         : Failed to fetch the lookup information of the device 0000001D 
03-04 09:59:35.869   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.869   554   692 D         : Failed to fetch the lookup information of the device 0000001D 
03-04 09:59:35.870   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.870   554   692 D         : Failed to fetch the lookup information of the device 0000001D 
03-04 09:59:35.871   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.872   554   692 D         : Failed to fetch the lookup information of the device 0000001E 
03-04 09:59:35.872   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.873   554   692 D         : Failed to fetch the lookup information of the device 0000001E 
03-04 09:59:35.873   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.874   554   692 D         : Failed to fetch the lookup information of the device 0000001E 
03-04 09:59:35.874   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.875   554   692 D         : Failed to fetch the lookup information of the device 0000001F 
03-04 09:59:35.876   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.876   554   692 D         : Failed to fetch the lookup information of the device 0000001F 
03-04 09:59:35.877   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.878   554   692 D         : Failed to fetch the lookup information of the device 0000001F 
03-04 09:59:35.878   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.879   554   692 D         : Failed to fetch the lookup information of the device 00000067 
03-04 09:59:35.879   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.880   554   692 D         : Failed to fetch the lookup information of the device 00000067 
03-04 09:59:35.880   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.880   554   692 D         : Failed to fetch the lookup information of the device 00000067 
03-04 09:59:35.881   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.883   554   692 D         : Failed to fetch the lookup information of the device 00000056 
03-04 09:59:35.884   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.884   554   692 D         : Failed to fetch the lookup information of the device 00000056 
03-04 09:59:35.884   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.885   554   692 D         : Failed to fetch the lookup information of the device 00000056 
03-04 09:59:35.886   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.887   554   692 D         : Failed to fetch the lookup information of the device 00000059 
03-04 09:59:35.887   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.887   554   692 D         : Failed to fetch the lookup information of the device 00000059 
03-04 09:59:35.888   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.888   554   692 D         : Failed to fetch the lookup information of the device 00000059 
03-04 09:59:35.889   554   692 E ACDB-LOADER: Error: ACDB ANC returned = -20
03-04 09:59:35.892   554   692 E hardware_cal: Failed to call ioctl  for  err=14
03-04 09:59:35.904   554   692 E ext_speaker: open_speaker_bundle: DLOPEN failed for /vendor/lib/soundfx/libspeakerbundle.so
03-04 09:59:35.925   554   692 W audio_hw_primary: adev_open: DLOPEN failed for libadm.so
03-04 09:59:35.943   554   554 W DeviceHAL: Error from HAL Device in function get_master_volume: Function not implemented
03-04 09:59:35.946   554  1010 W DeviceHAL: Error from HAL Device in function get_master_mute: Function not implemented
03-04 09:59:35.948   554  1010 W DeviceHAL: Error from HAL Device in function set_master_volume: Function not implemented
03-04 09:59:35.951   554   692 W DeviceHAL: Error from HAL Device in function set_master_mute: Function not implemented
03-04 09:59:36.215   554   692 W DeviceHAL: Error from HAL Device in function open_input_stream: Invalid argument
03-04 09:59:36.222   554   692 W DeviceHAL: Error from HAL Device in function open_input_stream: Invalid argument
03-04 09:59:36.374   554   692 W DeviceHAL: Error from HAL Device in function set_master_mute: Function not implemented
```

**Comment by ix5** [comment]
Should be fixed by https://github.com/sonyxperiadev/device-sony-tone/pull/163

**Comment by richardtullberg** [comment]
Hi @ix5 ,

sorry for the long wait but this was a hard nut to crack but the latest software and the latest binaries should fix this issue. Could you check that it fixed it for you? It is working now for me.

BR Richard

**Comment by ix5** [comment]
Hey @richardtullberg thanks for taking the time and sorry to keep you waiting, but I haven't forgotten to check up on it.
I am pretty sure the v5 binaries did not solve the issue but will confirm later today.

I have a writeup waiting for approval that I can then share with you.
The main issue seemed to be messed-up handling of `num_tx_channels`(15 instead of 1) for bluetooth in `q6voice.c`, which gets loaded by [voc_get_tx_rx_topology()](https://github.com/sonyxperiadev/kernel/blob/2637f52c94db33b498c6cc6c01df04fd2dde677c/techpack/audio/dsp/q6voice.c#L2421)
So something might have gone wrong during the techpack import... or an acdb is simply wrong.

These lines are especially weird:
```
voice_send_cvp_create_cmd: early: v->dev_rx.no_of_channels = 15
voice_send_cvp_create_cmd: early: v->dev_tx.no_of_channels = 15
```
But later:
```
voice_send_cvp_device_channels_cmd: cvp_set_channels:   rx_num_channels=1, tx_num_channels=15
```

**Comment by ix5** [comment]
Can share the writeup now, here it is @richardtullberg [sx.ix5.org: Bluetooth audio debugging](https://sx.ix5.org/info/post/bluetooth-audio-debugging/)

Just did a test run with v6 blobs. When I revert https://github.com/sonyxperiadev/device-sony-tone/pull/163 and push the file to the device, the issue re-appears, so the blobs have not been fixed as far as I can tell.
(And how would new blobs affect the `.acdb` files in [device-sony-kaguar/.../acdbdata/](https://github.com/sonyxperiadev/device-sony-kagura/tree/master/rootdir/vendor/etc/acdbdata) anyway... ;)
