### ISSUE TITLE
[Loire] 3 amp chargers doesn't work

### ISSUE THREAD

**Issue by maluus** [sonyxperiadev/bug_tracker#279]
Platform: Loire 
Device: Kugo 
Kernel version: 4.9
Android version: 9.0 

Description:
Xperia X Compact doesn't charge with 3.0 amp fast chargers. 2.0, 2.1 amp chargers works. 1 amp chargers works till certain point and after that constantly cuts power after 44-45%. See attached log which includes both 3 amp and 1 amp (after 45%) charging attempts.

Symptoms:
When charger connected at first begins to charge like 1 sec. then charging light goes off. Battery stat shows no charging but battery icon shows like charging.

How to reproduce:
Connect 3 amp charger. Connect 1 amp charging until 44-45%
[logcat_12-16-2018_15-41-17.txt](https://github.com/sonyxperiadev/bug_tracker/files/2702158/logcat_12-16-2018_15-41-17.txt)

[charging_dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/2705474/charging_dmesg.log)

**Comment by lubik1** [comment]
can confirm the same problem on Suzu (loire)

**Comment by kholk** [comment]
The Loire platform does not support the new QuickCharge standard by hardware, so that's totally normal.

**Comment by maluus** [comment]
Which standards and what changed? It was working until the time when beta v3 binaries published.
________________________________

**Comment by kholk** [comment]
Perhaps I don't understand the issue.
Please post a dmesg. The logcat is pretty useless here :P

I can guess, around the v3 release the kernel was updated, maybe something went wrong.

**Comment by maluus** [comment]
OP updated. You can find dmesg in the first post.

**Comment by jerpelea** [comment]
thid platform should not support the feature!

**Comment by harryharryharry** [comment]
@jerpelea According to Sony's own website Sony X Compact _does_ support QC3.0:
https://support.sonymobile.com/us/xperiaxcompact/faq/battery,-power-&-charging/02310188014550f700148fcce243e002e57/

**Comment by maluus** [comment]
Sure it supports because my phone came with a qc3 charger out of the box. But I think it's to do with 4.9 kernel. Because it was working with 4.4 kernel even with pie.
________________________________

**Comment by Gray47Maxx** [comment]
Iirc even suzu supports it. At least, in stock 6.0 fw... And in 2016 white papers

**Comment by kholk** [comment]
Wait a minute.
I think we have to reopen this issue.

The QC3.0 - supported or not - is an evolution of QC2.0, so on an unsupported platform it should _anyway_ charge the device, even if it falls back to a lower amperage... but the device is not charging at all.

This is a bug.

I'll look at it whenever I'll get some time to.

**Comment by harryharryharry** [comment]
Thanks. You're right, stock and even omnirom 8.1 do indeed work, although at a lower amperage (~1 to 1.5 as I recall). But omnirom 9: *crickets chirping* (only the led indicator goes on for about 2 seconds)

**Comment by maluus** [comment]
As I stated in my previous posts if its not something that 4.9 kernel restricts somehow then it should normally fully benefit from qc3. I had just thought over jerpeleas statement that for some reason 4.9 kernel restricts qc3 working on loire. Anyway I had given up builds and tests after jerpeleas comment but although the problem exists for all the loire users, if needed I can start to build, test and provide necessary logs.
________________________________

**Comment by jerpelea** [comment]
please provide logs from 8.1 and 9.0 to speedup the investigation

**Comment by harryharryharry** [comment]
I've saved dmesg-snippets during cable attachment to a qc3 charger from stock and omni8.

dmesg-snippet from stock (F5321 34.4.A.2.118) with [genesis kernel](https://forum.xda-developers.com/x-compact/development/kernel-xc-genesis-kernel-v1-01-t3525060) (to get root):
https://del.dog/ucikonogim

dmesg-snippet from omni8:
https://del.dog/uqalaqojus

And this is a full dmesg I just took from omni9:
https://del.dog/yagiqonovo

**Comment by maluus** [comment]
9.0 logs are in first post. You can find attached 8.0 stock rom dmesg log. I plugged in and out a few times before taking the log.
________________________________

**Comment by sjllls** [comment]
This issue still exists on Suzu, phone can't charge with a QC3.0 charger.
AOSP build on 2019.2.8.
@jerpelea

**Comment by maluus** [comment]
Lots of commits and merges lately. Is there a possibility that some of them somehow affects this issue?

**Comment by sjllls** [comment]
> Lots of commits and merges lately. Is there a possibility that some of them somehow affects this issue?
> [Late edit]
> @kholk

Issue still exists on Android 9, OEM V7, built on 2019.3.23.
My charger is UCH10, only support QC2.0.
[SuzuCharge.log](https://github.com/sonyxperiadev/bug_tracker/files/3022706/SuzuCharge.log)

Log uploaded.

**Comment by maluus** [comment]
I think devs couldn't have time to look at the problem yet. Fingers crossed.

**Comment by harryharryharry** [comment]
@maluus, Pavel recently made a commit that fixes this issue:
https://github.com/bartcubbins/kernel_loire/commit/2b5fdc84600620e8ae146a7c888f7c9ebfbe397d

My kugo now charges at 2A with a QC3 charger. Thanks @bartcubbins !

**Comment by maluus** [comment]
Oh at long last. I can start building again.
________________________________

**Comment by bartcubbins** [comment]
@jerpelea fixed by https://github.com/sonyxperiadev/kernel/pull/1972

**Comment by maluus** [comment]
@harryharryharry, Today I synced the source and built but problem persist on my side. Did you cherry picked the commit or compiled directly from the source?

**Comment by harryharryharry** [comment]
Since it was such a small modification, I dumbly added the line in the commit to the appropriate place in msm8956-loire-common.dtsi in my sources. 
Only syncing your sources will not be enough, since this is still just a commit from a repo from Pavel's github. So either manually add it or cherry-pick the commit from Pavel's repo.

**Comment by maluus** [comment]
I checked that the code is there and rebuilt now I'll check if it works.
________________________________

**Comment by bartcubbins** [comment]
just tried and can't reproduce the issue anymore

**Comment by bartcubbins** [comment]
please, provide me dmesg and I will take a look as soon as possible

**Comment by maluus** [comment]
Dmesg attached. I hope it helps. I plugged it in different chargers and pc before taking the log. (proprietary qc3 charger, other generic qc3 charger, and ipad charger and pc.)

[dmesg.txt](https://github.com/sonyxperiadev/bug_tracker/files/3153583/dmesg.txt)

**Comment by bartcubbins** [comment]
@maluus please update your kernel. you have outdated kernel.  (commit 96e6d64d2d0c) https://github.com/sonyxperiadev/kernel/commit/96e6d64d2d0cda43e77ef5274bd1118362c1d0c2
[    0.000000] Linux version 4.9.170-g96e6d64d2d0c-dirty

**Comment by bartcubbins** [comment]
@maluus looks like you use prebuilt kernel. change this to true and try once again
https://github.com/sonyxperiadev/vendor-sony-kernel/blob/aosp/LE.UM.2.3.2.r1.4/KernelConfig.mk#L15

**Comment by maluus** [comment]
Yeah I completely forgot it. My bad. Will try again.

**Comment by kholk** [comment]
@bartcubbins that was great man, thanks :D

**Comment by bartcubbins** [comment]
@kholk 😉

**Comment by maluus** [comment]
I forgot to thank for all your valuable efforts
@kholk @jerpelea @bartcubbins @harryharryharry
