### ISSUE TITLE
[Tama/Apollo] H8324 XZ2C Dual - Touchscreen not working on AOSP 9

### ISSUE THREAD

**Issue by NotLikelyNo** [sonyxperiadev/bug_tracker#351]
**Platform:** Tama
**Device:** Apllo (H8324 XZ2C Dual)
**Kernel version:** 4.9.155
**Android version:** 9.0.0_r31

**Description**
Touchscreen does not work (does not react to touching) after building AOSP 9 with the attached script (adding CONFIG_TOUCHSCREEN_SYNAPTICS_TCM=y as per https://github.com/sonyxperiadev/bug_tracker/issues/262).

[xz2c.sh.txt](https://github.com/sonyxperiadev/bug_tracker/files/2920558/xz2c.sh.txt)

**Symptoms**
Touchscreen is non-responsive.

**How to reproduce**
Build AOSP and kernel with above build script on a device identical to mine. dmesg from AOSP (i.e. with non-functioning touchscreen attached) as well as bug report from vendor FW (i.e. with functioning touchscreen).

[AOSP9.dmesg.txt](https://github.com/sonyxperiadev/bug_tracker/files/2920547/AOSP9.dmesg.txt)

[bugreport-aosp_h8324-PQ2A.190205.001-2019-02-17-22-16-48.txt](https://github.com/sonyxperiadev/bug_tracker/files/2920549/bugreport-aosp_h8324-PQ2A.190205.001-2019-02-17-22-16-48.txt)

**Comment by rfeltstykket** [comment]
This is affecting me too with both the v6 and v7 binaries after building AOSP 9, following the AOSP build instructions from the open devices website.

**Comment by jerpelea** [comment]
Hi 
thanks for the report 
I tried to get a device with your touch without success 

I can see this line in your dmesg
[    4.477541] clearpad clearpad: (clearpad_touch_config_dt:6078) no chip_id 
[   69.680924] clearpad-i2c 2-002c: clearpad_i2c_set_page: set page failed: -107.

**Comment by SGMcejo** [comment]
Same here. No aosp based custom rom seems to work for my device. I as well tried to build it with said line added, but with no luck.

**Comment by kostya-fr** [comment]
Same problem after building android-9.0.0_r37 on first boot I have only message "There's an internal problem with your device. Contact your mlanufacturer for details" 

Could somebody helps me please ?

**Comment by MartinX3** [comment]
@kostya-fr "Internal problem" sounds like another problem.
Could you try your build *without* a sdcard?
And then with selinux permissive?

So we could see if it is either a problem with your sdcard file system or the selinux policy.

**Comment by stefanhh0** [comment]
@kostya-fr 

On a fresh build the message should no longer occur, it should have been fixed with sonyxperiadev/kernel@1609074128522d5f20d9d07f04ea3b43904014c2

See also the discussion starting here: https://github.com/sonyxperiadev/bug_tracker/issues/393#issuecomment-493311056

**Comment by kostya-fr** [comment]
Ok first time I built aosp_h8324-userdebug and now I tryed aosp_h8324-eng and it works better ... no error message but touchscreen still not working. :/ 

[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/3205780/dmesg.log)

**Comment by stefanhh0** [comment]
@kostya-fr the dmesg.log shows that at least your kernel is still on an older commit from two days ago: sonyxperiadev/kernel@46fbfbf358fe

Update with repo_update.sh and delete afterwards kernel/sony/msm-4.9/common-headers to get a newly built kernel on latest sources.

I don't know if that helps regarding the touchscreen issue but at least then also aosp_h8324-userdebug builds should no longer show the internal problem message.

**Comment by kostya-fr** [comment]
So I did :

```bash
rm -r ~/android/kernel/sony/msm-4.9/common-kernel
make clean
./repo_update.sh && source build/envsetup.sh && lunch
```
choosing 23 -> aosp_h8324-eng

I don't know why but while the make it says that `kernel/sony/msm-4.9/common-kernel/kernel-dtb- is missing` but I have `kernel/sony/msm-4.9/common-kernel/kernel-apollo` so I do that and it works :
```bash
cp kernel/sony/msm-4.9/common-kernel/kernel-dtb-apollo kernel/sony/msm-4.9/common-kernel/kernel-dtb-
```

and then:
```bash
make -j 4 bootimage 
make -j 4
```

Flashed : 
```bash
fastboot --disable-verity --disable-verification 
fastboot --disable-verity --disable-verification flash vbmeta out/target/product/apollo/vbmeta.img
fastboot flash boot_a out/target/product/apollo/boot.img
fastboot flash dtbo out/target/product/apollo/dtbo.img
fastboot flash system_a out/target/product/apollo/system.img
fastboot flash vendor out/target/product/apollo/vendor.img
fastboot flash oem SW_binaries_for_Xperia_Android_9.0_2.3.2_v8_tama.img
fastboot flash vendor out/target/product/apollo/vendor.img
fastboot flash userdata out/target/product/apollo/userdata.img
```

But still no touchscreen :/
[dmesg2.log](https://github.com/sonyxperiadev/bug_tracker/files/3208407/dmesg2.log)

**Comment by stefanhh0** [comment]
@kostya-fr today  several changes have been made to the repos, probably you synced when the setup of the repos has not yet finished properly. Therefore you should resync to get your repos into a clean state. 

I failed to resync this evening (CET) via `./repo_update.sh` it gave me some error. Therefore I had to do first a force-sync via: 
`repo sync --force-sync -j 8` 
After that I ran again `./repo_update.sh` which then succeeded.

I usually sync the repos after regular CET business hours then the chances are good that the repos are in a usable state. Usually over the day several things are integrated into various git repos that may have inter-dependencies and therefore there is always a risk to sync to something in-between which then does not build or has intermediate issues that are just "temporary artifacts".

You are using a flash procedure that is different then what is documented in https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-p-9-0-0. But since I don't own an apollo myself I can't say whether there is a problem with what you do or if that is totally valid.

The dmesg2.log shows that your kernel is now on sonyxperiadev/kernel@6f8c28697397 which is even older then the previous kernel you have used, that is due to the inconsistent state of the repos and the manual copying.

When you are back to a clean repo state you should rebuild again. Also v9 oem will be released soon, it probably makes sense that you wait with your next build attempt until v9 has been released. It might be the case that v8 is still compatible with all the latest changes but some changes may require v9 already. 

Since the ticket here is still open you can expect that a bugfix will be provided at some point in time for the touchscreen issue of the apollo device.

**Comment by kostya-fr** [comment]
@stefanhh0 Thanks for your help. I will try v9 tonight, hope it gona work. 

About my flash procedure I based on https://forum.xda-developers.com/xperia-xz2/development/aosp-aosp-8-1-h8266-t3843269 , bacause after trying [official one ](https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-p-9-0-0#tutorial-step-2) it doesn't work and recovery.img isn't generated so I flashed all *.img files. 

Curiose thing, after rolling back to Xperia Android my camera is black but can taking pictures "fine" ... Hope I didn't screw up the camera

**Comment by MartinX3** [comment]
@kostya-fr for the camera please look at the XDA xz2 twrp thread.

**Comment by mmarmm** [comment]
@kostya-fr I'm in the same boat, unlocked with a later Xperia Android version and my camera preview is black in Xperia, no touchscreen in AOSP. I'll see if I can build and try different combinations this week to help.

**Comment by kostya-fr** [comment]
Hi! This night I built AOSP with following script : 

```
branch=android-9.0.0_r37
binary=SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_tama.img
```
[build_clean_aosp.txt](https://github.com/sonyxperiadev/bug_tracker/files/3227521/build_clean_aosp.txt)


And after flashing I have "System UI isn't responding. Close or Wait", even volume buttons don’t work, no touchscreen, black background...
[dmesg3.log](https://github.com/sonyxperiadev/bug_tracker/files/3226045/dmesg3.log) based on [https://github.com/sonyxperiadev/kernel/commit/69cc32601555](https://github.com/sonyxperiadev/kernel/commit/69cc32601555)

After I rebuilt Kernel [with official guide](https://developer.sony.com/develop/open-devices/guides/kernel-compilation-guides/how-to-build-and-flash-a-linux-kernel-for-aosp-supported-devices) (from step 2)

And after flashing I have same behavior (System UI isn't responding, black background… )
[dmesg4.log](https://github.com/sonyxperiadev/bug_tracker/files/3227547/dmesg4.log) based on [https://github.com/sonyxperiadev/kernel/commit/9ab03839fa99](https://github.com/sonyxperiadev/kernel/commit/9ab03839fa99) 

Still no success :'( Did I something wrong in my script ? Should I chose an other branch? In XDA forum I saw that r35 should be stable, but it doesn’t work for me too…

**Comment by jerpelea** [comment]
please use flashftool and update the sw to the last provided version. Boot the device with a SIM card then reboot and flash AOSP.

**Comment by kostya-fr** [comment]
@jerpelea I used flashtool Emma on W10 and flashed `H8234 52.0.A.3.84 Customized_UK 1313-5469 R2B User-Live COM` the top available when I connect my device

**Comment by MartinX3** [comment]
The newest is 52.0.A.8.50 (May 2019)
https://xpericheck.com/device/H8314
Maybe he want that you use http://www.flashtool.net/index.php

I prefer to use newflasher from XDA (I downloaded the firmware with xperifirm from xda)

**Comment by jerpelea** [comment]
@kostya-fr please use the version provided in Emma because that one has been tested by us

**Comment by kostya-fr** [comment]
@jerpelea So `H8234 52.0.A.3.84 Customized_UK 1313-5469 R2B User-Live COM` ? Why I can't get  52.0.A.8.50 the last one ? 
@MartinX3 I tried  your Flashtool but my device(H8324) is missing in the list of devices

**Comment by MartinX3** [comment]
Should still flash your device
I prefer newflasher from xda

**Comment by kostya-fr** [comment]
@MartinX3 With Flasher i have this error : [flashtool_2019-05-29_05-27-13.log](https://github.com/sonyxperiadev/bug_tracker/files/3233194/flashtool_2019-05-29_05-27-13.log)
And newflasher.exe says : 
```bash
Optional step! Type 'y' and press ENTER if you need GordonGate flash driver, or type 'n' to skip.
This creates GordonGate.7z archive in the same dir with newflasher.exe!
n
Device path: \\?\usb#vid_0fce&pid_b00b#5&33eb7b70&0&1#{a5dcbf10-6530-11d2-901f-00c04fb951ed}
Class Description: SOMC Flash Device
Device Instance Id: USB\VID_0FCE&PID_B00B\5&33EB7B70&0&1


Optional step! Type 'y' and press ENTER if you want dump trim area, or type 'n' and press ENTER to skip.
Do in mind this doesn't dump drm key since sake authentifiction is need for that!
n
ERROR: TIMEOUT: failed with error code 997 as follows:
Une opÚration dÆentrÚe/sortie avec chevauchement est en cours dÆexÚcution.
 - Error write! Need nBytes: 0x18 but done: 0x0
nBytes[0x0]:

 - Error writing command getvar:max-download-size!

End. You can disconnect your device when you close newflasher.exe
```

**Comment by MartinX3** [comment]
And with newflasher?
https://forum.xda-developers.com/crossdevice-dev/sony/progress-newflasher-xperia-command-line-t3619426

**Comment by stefanhh0** [comment]
I guess, it would  be better if you stick to emma for now. With alternative flashtools like newflasher you may run into different issues that are kind of unnecessary, especially in the context of this issue. The alternative flashtools like newflasher are a little more complicated to handle and you can do wrong things with them. Plus this issue tracker isn't anyway the place to deal with problems of those other flashtools. So for now in order to make things as simple as possible and avoid additional confusion and to get to a well known AOSP baseline forget newflasher and other alternatives flashtools and stick to emma as your preferred flashtool.

> Why I can't get 52.0.A.8.50 the last one ?

That question has already been answered by Alin:
> please use the version provided in Emma **because that one has been tested by us**

Emma offers sometimes more than one Version (e.g. in case of XZ1C). Not all of the versions found in emma are always considered as stable. Reason for that is that they contain drivers that are not tested together with current AOSP,  as Alin already told. There can be even Versions provided in emma with drivers that are known to introduce instabilities and errors together with current AOSP (like it is currently the case with XZ1C). 

If there is just one version provided in emma it is clear which version to flash, anyway you have to choose the variant with userdata wipe! If there is more than one version offered, report them here so that someone can clarify which to actually choose - I can't unfortunately since I don't own a XZ2C.

After you have flashed the stable stock-rom with emma inclusively userdata wipe, boot the phone with inserted sim into that stock-rom. After that, reboot the phone into fastboot mode and verify via fastbooot getvar version-baseband that you are on the expected version-baseband. Write down the exact version-baseband of your phone and report it here in case your touch-screen still isn't working. After you have successfully verified that you are on the expected version-baseband  continue flashing a consistent recent build of AOSP and then re-check the function of your touch-screen. I keep the fingers crossed that your touch-screen will work then again.

**Comment by Grooot56** [comment]
Just downloaded and installed on June, 2nd on a Sony xz2 compact dual sim H8324, with the files provided in the xda developers tutorial and SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_tama. I do not get any error message but the touchscreen does not respond at all. The side buttons work. I have not managed to install the dual sim patcher yet. I run Linux Mint 18.3 so I cannot use Emma.
Thank you for your support.

**Comment by MartinX3** [comment]
The problem was on the roms directly compiled as dual sim variant, too. :)

**Comment by kostya-fr** [comment]
With official Emma flashotool I got this :
![image](https://user-images.githubusercontent.com/12466693/58953151-e5fdc080-8795-11e9-8988-ff69c61aad24.png)

@stefanhh0 

```
fastbooot getvar version-baseband
version-baseband: 1311-5320_52.0.A.3.84
```

So I think I did it right, no ?

**Comment by stefanhh0** [comment]
@jerpelea can you answer the question which SW version should be used together with AOSP? Is it:
52.0.A.3.84 or  51.A.11.51?

**Comment by MartinX3** [comment]
It must be that some xz2c have a different touch hardware or hardware revision which works with stock but not with the sodp kernel
The problem exists since a long time.

**Comment by stefanhh0** [comment]
@kostya-fr You just could give it a try and switch to  51.A.11.51 (SW Update Content Erase), after that reflash current AOSP. At least on xz1c it makes a huge difference in what works and what not depending which SW Update was used as basis, maybe that is also true for xz2c...

In case different hw resp. hw revs. are used for some xz2c then that could very well be a good candidate.

**Comment by swisssam** [comment]
It seems like I am affected by the same problem. Is there anything I can do to debug this?

**Comment by kostya-fr** [comment]
Sorry I was a little busy this week. 
@stefanhh0 So I gave a try for 51.A.11.51 with Emma and then flashed  `android-9.0.0_r37` with OEM `SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_tama.img`, but on first boot I get black screen with"System UI isn't responding" message and after forced reboot I have the same issue(no touchscreen, but other buttons, sounds... seems working) ... 


[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/3289653/logcat.log)
[logcat_radio.log](https://github.com/sonyxperiadev/bug_tracker/files/3289654/logcat_radio.log)
[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/3289655/dmesg.log)

**Comment by hosler** [comment]
I am able to replicate the issue with my xz2c. My touchscreen will not work after installing latest omnirom

**Comment by masonfaulkner** [comment]
I'm also affected by the touchscreen problem with the xz2c H8314 with Omnirom and AOSP. I'm also willing to test with mine.

**Comment by Sputnik2a** [comment]
I'm also affected by the touchscreen issue with the H8314 device. I have the issue with Omnirom and AOSP. I deliver logs after resolved my build issues with android-9.0.0_r44 branch. I don't use this device with stock ROM so I can also do any test with it.

**Comment by lapineige** [comment]
Same issue here: touchscreen not working on both AOSP and OmniROM.

I installed it from a XZ2 Compact Dual Sim, version 52.0.A.3.50, with @MartinX3 files from May (as I understood they are the ones I should use with my version).

How can I deliver the logs ? With adb logcat ?

**Comment by MartinX3** [comment]
@lapineige I recommend the newest stock firmware version, but in this case it won't fix this issue ticket on your side. :)

About the logs:
Linux
```
sudo ./adb shell dmesg > dmesg.log
sudo ./adb shell logcat > logcat.log
```
Windows
```
adb.exe shell dmesg > dmesg.log
adb.exe shell logcat > logcat.log
```

**Comment by lapineige** [comment]
I can't use latest firmware, it is still not available with OTA. And online, only the version .83 is available (for French phones).

I can't use adb, as the devices don't allow me to use USB debugging… OmniROM even show a pop-up to activate it, but I can't touch the screen…

**Comment by lapineige** [comment]
OK with AOSP it's working, but only logcat, not dmesg.

I don't see anything when I touch the screen. Do you want the full log ?

**Comment by MarijnS95** [comment]
@lapineige `dmesg` is the most useful as [the dmesg from @kostya-fr](https://github.com/sonyxperiadev/bug_tracker/issues/351#issuecomment-502017324) shows there's an issue with the i2c endpoint not being connected (`clearpad-i2c 2-002c: clearpad_i2c_set_page: set page failed: -107`) - yours is most likely the same.

The interesting thing is that the first errors occur in `post_probe`, which is [disabled on stock Apollo](https://github.com/sonyxperiadev/kernel-copyleft/blob/072616505d51c0aeadf598e1bbc155df983c5b44/arch/arm64/boot/dts/somc/somc-tama-touch_apollo.dtsi#L24). This probe is apparently retried every time, and may be the cause for the issue.

**Comment by lapineige** [comment]
But I can't use it :(

**Comment by MarijnS95** [comment]
@lapineige I'm aware of that. In fact, I'm already in contact with @MartinX3 who supplies your images to deliver one with this feature disabled.

Again, I doubt it'll work, but it's a start.

Also note that you can embed your adb key in `/adb_keys` on the rootimage, in case you're building AOSP yourself. Or put it in the right location `/data/misc/adb/adb_keys` from recovery.

**Comment by lapineige** [comment]
What is this `adb_keys` ?

I actually can't use recovery, I don't know why but I can't boot TWRP, and I can't flash anything into recovery (partition not found or something like that).

**Comment by MartinX3** [comment]
thank you for the hint @MarijnS95 
Here is a fresh compiled DTBO.

Installation instructions
```
fastboot flash dtbo dtbo.img
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
```

The second command is needed to load the modified dtbo, because my builds are using the AvB2 vbmeta partition to protect your data integrity.

Now we need another full dmesg.log from you.
And a logcat.log.
You can use either TWRP or the normal android image.
I assume that TWRO should be easier for you, since it is rooted by default.
[dtbo.img.zip](https://github.com/sonyxperiadev/bug_tracker/files/3480654/dtbo.img.zip)

**Comment by lapineige** [comment]
> On AOSP, try adb root before adb shell dmesg.

Ok this worked !

I'll provide the full logs.

For now, I can this these errors
> i2c_geni 894000.i2c: i2c error :-107
and
> clearpad clearpad: (clearpad_process_irq:4657) error (icount=0 rc=-16)

**Comment by MartinX3** [comment]
@lapineige 
And don't forget to test https://github.com/sonyxperiadev/bug_tracker/issues/351#issuecomment-519425891 :)

**Comment by lapineige** [comment]
> I assume that TWRO should be easier for you, since it is rooted by default.

What do you mean ?
I can flash TWRP as boot image, and it will have root access ?
(in the past TWRP touchscreen was working)

**Comment by MartinX3** [comment]
The SODP custom rom touch screen was working?
Or do you mean the stock rom touch screen?

Please use
```
fastboot reboot bootloader
fastboot boot twrp.img
```
If you want to use TWRP.
And make sure that you flashed one of the provided SODP based custom ROMs on XDA together with the SODP TWRP.

**Comment by lapineige** [comment]
What is SODP ?

Ok I did: 
```
fastboot reboot bootloader
fastboot flash dtbo dtbo.img
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
fastboot boot twrp.img
```
(is that correct ?)

And I'm on bootloader (black) screen, with blue led, nothing else, as before.

**Comment by MartinX3** [comment]
I mean you flashed either OmniROM or SonyAOSP from XDA first (the custom roms with the touch problems) :)
https://forum.xda-developers.com/xperia-xz2/development/aosp-aosp-8-1-h8266-t3843269
https://forum.xda-developers.com/xperia-xz2/development/rom-omnirom-9-0r30-t3897951

The twrp you need to use is the custom rom one from there, it should have the same touch problems
https://forum.xda-developers.com/xperia-xz2/development/recovery-twrp-3-2-2-0-touch-recovery-t3821597

But instead of using the dtbo.img file from xda, you use the zipped one I uploaded here, together with the vbmeta command :) (the vbmeta file is part of the rom download on xda)

**Comment by MartinX3** [comment]
But just flash the dtbo & vbmeta, reboot and take a dmesg would be the easiest part, since you achieved "adb root" on the normal, touchless android system. :)

**Comment by lapineige** [comment]
Ok, then yes I did flash AOSP (and OmniROM, but AOSP in that case).

I think I used the TWRP that you provided in your download link on XDA.

**Comment by MartinX3** [comment]
I'm curious about the dmesg log result :)

**Comment by lapineige** [comment]
Here it is https://vps.lapineige.fr/privatebin/?e5c41e773c81808a#aafHIcNSZR/X4eUAUfAHOcfKgO5WjNBTbHM/HTZzwYo=

**Comment by MartinX3** [comment]
What about the touch @lapineige ?

Now the `-107` is missing and I see a
`[    1.867724] clearpad-i2c 2-002c: clearpad_i2c_probe: sucess`

**Comment by lapineige** [comment]
Touch not working.

**Comment by MarijnS95** [comment]
As expected, it doesn't change anything. Apparently stock manually starts the post probe from shell after inserting the modules.

So, someone needs to figure out why the i2c returns `-ENOTCONN`.

**Comment by MartinX3** [comment]
We maybe found the issue but need to discuss it internal with the team, please stay tuned @lapineige  and the others. :)

**Comment by lapineige** [comment]
I can confirm custom ROM TWRP as no functional touchscreen.

**Comment by MartinX3** [comment]
And again we'll need a fresh dmesg.log with the following files from you @lapineige 
:)

[apollo.zip](https://github.com/sonyxperiadev/bug_tracker/files/3481636/apollo.zip)

Installation instructions:
```
fastboot flash boot boot.img
fastboot flash dtbo dtbo.img
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
```

**Comment by lapineige** [comment]
Wow, already ! :smiley:

I flashed it, rebooted, I'm stuck on Sony logo, without adb right now. Is it expected ?

**Comment by MartinX3** [comment]
Woops, yes, it can't boot
I try to make a kernel with july security patch level.
The google rollback protection stops the booting.

**Comment by MartinX3** [comment]
And again we'll need a fresh dmesg.log with the following files from you @lapineige 
:)

[apollo.zip](https://github.com/sonyxperiadev/bug_tracker/files/3481974/apollo.zip) "2019-08-05" security patch level

Installation instructions:
```
fastboot flash boot boot.img
fastboot flash dtbo dtbo.img
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
```

**Comment by lapineige** [comment]
It doesn't boot by itself.
I'll try to flash AOSP with those files.

**Comment by MartinX3** [comment]
I think I better provide an august sony aosp on xda today xD

**Comment by lapineige** [comment]
But would I need a more recent firware version, or could I already use more recent builds ?
(right now I'm using your builds from May)

**Comment by MartinX3** [comment]
It must be my july build to work :)

**Comment by lapineige** [comment]
Ok !
Then I'll download it :)

**Comment by lapineige** [comment]
It boots ! :D

AOSP is starting, still no touchscreen, here is the dmesg log : https://vps.lapineige.fr/privatebin/?3567a4e19ac27833#9WJPnugfz+ts72Ngscs/62COfODlGI97pWh4bf2S9Po=

**Comment by MartinX3** [comment]
Hey @lapineige 
I made you a new debugging build, usable together with the new august sonyaosp build on xda

[apollo.zip](https://github.com/sonyxperiadev/bug_tracker/files/3485595/apollo.zip) Security patch 2019-08-05

It will now give us debug output from the i2c and tcm driver.
Of course we need again a dmesg.log. :)

**Comment by MartinX3** [comment]
Ping @lapineige for updated build :)

**Comment by Sputnik2a** [comment]
Hi Martin, I have flashed 52.0.A.8.131 your August Sony aosp from XDA and the debug build images. I don't see any clearpad* message dmesg.log but

```
[    0.642706] dsi_panel_driver_parse_gpios: failed get touch-vddio-en gpio
[    0.642822] dsi_panel_driver_parse_gpios: failed get touch-int-gpio
[    0.642890] dsi_panel_driver_parse_gpios: failed get vddio-gpio
[    0.643006] dsi_panel_driver_parse_gpios: disp dcdc en gpio not specified
[    0.643070] dsi_panel_driver_parse_gpios: failed get disp error flag gpio
...
[    2.078694] i2c_geni 894000.i2c: i2c error :-107
[    2.078803] synaptics_tcm_i2c 2-003c: syna_tcm_i2c_read (line 379): Transfer attempt 1 failed
```

[debug_apollo.zip](https://github.com/sonyxperiadev/bug_tracker/files/3488920/debug_apollo.zip)

**Comment by MarijnS95** [comment]
@Sputnik2a That's perfect. We disabled the Clearpad driver intentionally to prevent any interference with the TCM driver while figuring out what's up.

Anyway, it looks like the extra `i2c` debugging got lost somewhere, most likely due to the driver using two separate systems to forward log statements :man_facepalming:. I'll get Martin to compile a new build.

The missing gpios _seem_ fine. `touch-vddio-en` is also missing on stock, the other two (`touch-int-gpio` and `vddio-gpio`) are not even retrieved according to the source code (this project has them for compatibility with other panels on different platforms).

For the time being we are not sure what the problem is. It _seems_ we have all the regulators, and the i2c pins are fine (equivalent to stock). Yet, something is missing somewhere that makes the TCM not respond over i2c, or return an error.

**Comment by MartinX3** [comment]
Dear @Sputnik2a and @lapineige 
Here is a new build and thank you for testing :))

http://www.dhsfileserver.de/ftp/MartinX3/Test%20Builds/SODP/Xperia%20XZ2%20Compact/Touch%20Issues/apollo_v2.zip

**Comment by Sputnik2a** [comment]
Done :-)

```
[1.890718] synaptics_tcm_i2c 2-003c: touchctrl_is_touch_powered: power status (touch ON, display ON)
[1.890724] synaptics_tcm_i2c 2-003c: syna_tcm_probe: Touch is Powered, try to lock power
[1.890736] synaptics_tcm_i2c 2-003c: syna_tcm_probe: Lock Power Ok
[1.907006] ufshcd-qcom 1d84000.ufshc: ufs_advertise_fixup_device : vid=0198, model=THGAF8G9T43BAIR, spec 

[2.091298] synaptics_tcm_i2c 2-003c: syna_tcm_i2c_read (line 379): Transfer attempt 1 failed
```
I found now 179 lines with 'synaptics_tcm_i2c'. The most of them are failed I2C read attempts.

[debug_apollo_v2.zip](https://github.com/sonyxperiadev/bug_tracker/files/3489218/debug_apollo_v2.zip)

**Comment by lapineige** [comment]
Do you want a log from me too ?

**Comment by lapineige** [comment]
I tested with OmniROM too, same result, but I guess it's expected.

**Comment by MartinX3** [comment]
We, that's the version without these testbuild changes :)
We just need to wait for @MarijnS95 
He's just busy with other tasks, too. :)

**Comment by lapineige** [comment]
Yeah that's fine :)
Good luck MarijnS95 :)

>We, that's the version without these testbuild changes. :)

I don't get it, you mean  you made some change to AOSP and not OmniROM ?

**Comment by MartinX3** [comment]
> > We, that's the version without these testbuild changes. :)
> 
> I don't get it, you mean you made some change to AOSP and not OmniROM ?

Just my brain/keyboard running amok.:P

**Comment by MartinX3** [comment]
Hey @lapineige & @Sputnik2a 
I made you a new debugging build, usable together with the newest sonyaosp build on xda

http://www.dhsfileserver.de/ftp/MartinX3/Test%20Builds/SODP/Xperia%20XZ2%20Compact/Touch%20Issues/apollo_v3.zip

Of course we need again a dmesg.log. :)

Installation Instructions:
```
fastboot flash boot boot.img
fastboot flash vendor vendor.img
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
```
The other files must be from the xda sonyaosp build.

**Comment by Sputnik2a** [comment]
Done. New logs, new luck :-)

[debug_apollo_v3.zip](https://github.com/sonyxperiadev/bug_tracker/files/3503229/debug_apollo_v3.zip)

**Comment by MarijnS95** [comment]
Well, at least we've got the GENI i2c driver logging working, but as expected it doesn't provide much information. After all, all the i2c operations occur in the QUP Serial Engine, which communicates back what's going on. If it says the slave (the panel in this case) is not responding, there's nothing else we can do or look at.

The odd thing is that the touch in Akatsuki does approximately the same thing, not responding under certain circumstances at start. However, it recovers after what's most likely an init/reset sequence.

Again, we have checked all the power supplies already and those seem in-check. The TCM driver is identical so it's pretty much impossible that we're missing a reset sequence somewhere.
At this point I'm out of ideas; we'll wait until our kernel magician returns from holiday and see whether he can come up with things to check/try :grin:. Sorry, the wait is going to be yet longer.

**Comment by MartinX3** [comment]
Hey @lapineige & @Sputnik2a 
I made you a new debugging build, usable together with the newest sonyaosp build on xda

http://www.dhsfileserver.de/ftp/MartinX3/Test%20Builds/SODP/Xperia%20XZ2%20Compact/Touch%20Issues/apollo_v4.zip

Of course we need again a dmesg.log. :)

Installation Instructions:
```
fastboot flash boot boot.img
fastboot flash vendor vendor.img
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
```
The other files must be from the xda sonyaosp build.

Let's pray! :dancer:

**Comment by Sputnik2a** [comment]
Hey, here are the fourth version of logs. For me it looks seamless as the third one. However every try is better as no try :smiley: 

[debug_apollo_v4.zip](https://github.com/sonyxperiadev/bug_tracker/files/3517228/debug_apollo_v4.zip)

**Comment by lapineige** [comment]
Hi, do you want the log from me too ?

**Comment by MarijnS95** [comment]
@lapineige Not necessary, one log tells me all we know.

Sorry for forgetting about this. That time allowed me to find some possible solutions though. During some local work on another platform a very similar issue occurred, and I'm hoping it's the same:
The panel gets the registers/GPIOs that regulate power to the incell, but is probed _after_ touch. Meaning the incell touch doesn't receive any energy until after it has been unsuccessfully probed.

Now I or someone else has to check if this even remotely applies to TCM (and why it is not an issue on Clearpad...), and fix it.

**Comment by lapineige** [comment]
Ok, good to know.
No problem, I wasn't available either (hence the absence of logs from me).

**Comment by MartinX3** [comment]
Hey @lapineige & @Sputnik2a 
I made you a new debugging build, usable together with the newest sonyaosp build on xda

http://www.dhsfileserver.de/ftp/MartinX3/Test%20Builds/SODP/Xperia%20XZ2%20Compact/Touch%20Issues/apollo_v5.zip

Of course we need again a dmesg.log. :)

Installation Instructions:
```
fastboot flash boot boot.img
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
```
The other files must be from the xda sonyaosp build.

**Comment by MarijnS95** [comment]
For good measure: this image _will not fix things_ again, unfortunately. I've stuffed the dsi incell panel driver with logs, just to see whether all the relevant regulators and gpios really get enabled/set. Upon very quick scrolling through the file it seems possible that the panel driver reports everything is powered on, when it in fact isn't (partially).

**Comment by Sputnik2a** [comment]
Good luck :-)

```
[1.458669] dsi_panel_driver_parse_gpios: failed get touch-vddio-en gpio
[1.458733] dsi_panel_driver_parse_gpios: failed get touch-int-gpio
[1.458852] dsi_panel_driver_parse_gpios: failed get vddio-gpio
[1.458969] dsi_panel_driver_parse_gpios: disp dcdc en gpio not specified
[1.459032] dsi_panel_driver_parse_gpios: failed get disp error flag gpio
...
[2.701396] @@@@ incell_get_power_status: status = 0x5
[2.701517] dsi_panel_driver_is_power_on: In-Cell on state
[2.701743] synaptics_tcm_i2c 2-003c: touchctrl_is_touch_powered: power status (touch ON, display ON)
[2.701748] synaptics_tcm_i2c 2-003c: syna_tcm_probe: Touch is Powered, try to lock power
[2.701754] @@@@ incell_power_lock_ctrl @@@@
[2.701870] @@@@ incell_power_lock @@@@
[2.701989] @@@@ incell_get_power_status: status = 0x7
[2.702203] dsi_panel_driver_is_power_on: In-Cell on state
[2.702321] synaptics_tcm_i2c 2-003c: syna_tcm_probe: Lock Power Ok
...
[28.845703] @@@@ dsi_panel_driver_pre_power_on @@@@
[28.845802] @@@@ dsi_panel_driver_power_on_ctrl @@@@
```

[debug_apollo_v5.zip](https://github.com/sonyxperiadev/bug_tracker/files/3585133/debug_apollo_v5.zip)

**Comment by MarijnS95** [comment]
Lol!
```
[    1.462590] @@@@ dsi_panel_driver_touch_power @@@@
[    1.462696] @@@@ dsi_panel_driver_touch_power_off @@@@
```
Then, a bit later
```
[    2.701396] @@@@ incell_get_power_status: status = 0x5
[    2.701517] dsi_panel_driver_is_power_on: In-Cell on state
[    2.701743] synaptics_tcm_i2c 2-003c: touchctrl_is_touch_powered: power status (touch ON, display ON)
[    2.701748] synaptics_tcm_i2c 2-003c: syna_tcm_probe: Touch is Powered, try to lock power
[    2.701754] @@@@ incell_power_lock_ctrl @@@@
[    2.701870] @@@@ incell_power_lock @@@@
[    2.701989] @@@@ incell_get_power_status: status = 0x7
[    2.702203] dsi_panel_driver_is_power_on: In-Cell on state
[    2.702321] synaptics_tcm_i2c 2-003c: syna_tcm_probe: Lock Power Ok
```
I think we hit the jackpot here. Let me investigate the driver in - say - an hour or two, and hope Martin can compile a new build for you guys :grin:

**Comment by lapineige** [comment]
Yeah, sounds good ! :smiley:

I can't flash anything until a few day, but I'll be happy to test a new build :)

**Comment by MartinX3** [comment]
Hey @lapineige & @Sputnik2a 
I made you a new debugging build, usable together with the newest sonyaosp build on xda

http://www.dhsfileserver.de/ftp/MartinX3/Test%20Builds/SODP/Xperia%20XZ2%20Compact/Touch%20Issues/apollo_v6.zip

Of course we need again a dmesg.log and this time a report if the touch works. :)

Installation Instructions:
```
fastboot flash boot boot.img
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
```
The other files must be from the xda sonyaosp build.

**Comment by Sputnik2a** [comment]
No touch :disappointed: communication via I2C failed.

```
[1.857828] @@@@ dsi_panel_driver_touch_power @@@@
[1.857933] @@@@ dsi_panel_driver_touch_power_on @@@@
[1.858127] incell_control_mode: FINISH - incell.status:0x5
[1.858234] @@@@ incell_get_power_status: status = 0x5
[1.858338] dsi_panel_driver_is_power_on: In-Cell on state
[1.858534] synaptics_tcm_i2c 2-003c: touchctrl_is_touch_powered: power status (touch ON, display ON)
[1.858537] synaptics_tcm_i2c 2-003c: syna_tcm_probe: Touch is Powered, try to lock power
[1.858538] @@@@ incell_power_lock_ctrl @@@@
[1.858640] @@@@ incell_power_lock @@@@
[1.858831] @@@@ incell_get_power_status: status = 0x7
[1.858934] dsi_panel_driver_is_power_on: In-Cell on state
[1.859128] synaptics_tcm_i2c 2-003c: syna_tcm_probe: Lock Power Ok
...
[2.059773] synaptics_tcm_i2c 2-003c: syna_tcm_i2c_read (line 379): Transfer attempt 1 failed
...
[2.320673] synaptics_tcm_i2c 2-003c: syna_tcm_read_message (line 1575): Failed to read from device
...
[2.600951] synaptics_tcm_i2c 2-003c: syna_tcm_i2c_write (line 417): Transfer attempt 1 failed
...
[2.871190] synaptics_tcm_i2c 2-003c: syna_tcm_reset (line 2915): Failed to write command CMD_RESET
...
[3.421015] @@@@ incell_power_lock_ctrl @@@@
[3.421150] @@@@ incell_power_unlock @@@@
[3.421367] @@@@ incell_get_power_status: status = 0x5
[3.421486] dsi_panel_driver_is_power_on: In-Cell on state
[3.421705] synaptics_tcm_i2c 2-003c: syna_tcm_probe: Unlock Power Ok

```
[debug_apollo_v6.zip](https://github.com/sonyxperiadev/bug_tracker/files/3585654/debug_apollo_v6.zip)

**Comment by MarijnS95** [comment]
Well that's unfortunate, but I should've seen it coming. I only enabled the GPIO that supplies the incell touch (controller?), but that power still has to come from _somewhere_ - I guess the panel regulators itself. So, I'll see about enabling the entire panel after checking stock and clearpad drivers. I didn't clearly see them doing this anywhere, but need to check more carefully again.

**Comment by MarijnS95** [comment]
Thanks to @MartinX3 we just checked what clearpad is doing on his Akari.

Aaand...

*It's cheating*

Literally, it succeeds the probe without ever talking over the i2c. Instead it has a `post probe` worker that runs _and fails_ a couple times until the panel itself "powers on" and gives the touch controller the reset sequence. Then things magically start to work.

Proposed fix and image incoming.

**Comment by MartinX3** [comment]
Hey @lapineige & @Sputnik2a 
I made you a new debugging build, usable together with the newest sonyaosp build on xda

http://www.dhsfileserver.de/ftp/MartinX3/Test%20Builds/SODP/Xperia%20XZ2%20Compact/Touch%20Issues/apollo_v7.zip

Of course we need again a dmesg.log and this time a report if the touch works. :)

Installation Instructions:
```
fastboot flash boot boot.img
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
```
The other files must be from the xda sonyaosp build.

**Comment by lapineige** [comment]
It WORKS ! :tada: :tada: :tada: \o/

**Comment by MartinX3** [comment]
Omfg i did fall from my chair

**Comment by lapineige** [comment]
Is it a crop in the image ?

And btw, you forgot that :
> And btw, where can we offer a bucket for the people working on solving this issue ? ;)

? :wink:

**Comment by MartinX3** [comment]
> Is it a crop in the image ?
> 
Yeah, it is normal, I recommend a gcam.
I linked a few in my XDA threads and actively use the one from gouster4. :)

> And btw, you forgot that :
> 
> > And btw, where can we offer a bucket for the people working on solving this issue ? ;)
> 
> ? wink
Thank you :)
But good question how that is handled at SODP :S
I don't find anything about donations there https://developer.sony.com/develop/open-devices/more-information/contribute-and-support/
So I don't know, feel free to do what you think is correct. :)

I will be happy to distribute fixed builds on xda after the code got refactured and merged into SODP. :)

**Comment by lapineige** [comment]
> Yeah, it is normal, I recommend a gcam.

What is it ?
(ok, maybe I'll search for this in the forum)

**Comment by MarijnS95** [comment]
Yeah, I expected it to work this time :slightly_smiling_face: 

Now comes the fun part though:
- Arguing why the incell+dsi panel driver is so ... ... ... We need to work on that.
- Fix that driver in a way that makes at least some sense (and addresses the rumored weirdness on clearpad).
- Testing what works best with both drivers. Probably a runtime check against the panel ID (which is also the most safe, we should go that way).

**Comment by MartinX3** [comment]
> > Yeah, it is normal, I recommend a gcam.
> 
> What is it ?
> (ok, maybe I'll search for this in the forum)

A google camera port compatible with SODP tama devices.
I put the links in the same post of the download links for SonyAOSP and OmniROM.
It uses the RAW camera possibilities and helps with its own processing algorithms.
It fixes problems at my side appearing with the current camera state.
Together with the focus workaround by kholk I compiled into the rom releases.

**Comment by lapineige** [comment]
But that might add some google tracking ? (does it work without Gapps ?)

**Comment by MartinX3** [comment]
> But that might add some google tracking ? (does it work without Gapps ?)

Sadly until now I didn't found a way to use this app without gapps.
It needs something from there and crashes otherwise. :(
But it helps a lot in terms of camera behaviour.

**Comment by lapineige** [comment]
Ok, then I'll wait for a better stock camera support, that's not a big deal, it still works :)

**Comment by MartinX3** [comment]
Hey @lapineige & @Sputnik2a 
I made you a new debugging build, usable together with the newest sonyaosp build on xda

http://www.dhsfileserver.de/ftp/MartinX3/Test%20Builds/SODP/Xperia%20XZ2%20Compact/Touch%20Issues/apollo_v7.zip

Of course we need again a dmesg.log and this time a report if the touch works. :)

We have now a single image for clearpad and tcm touch.
I already tested it on my akari clearpad and the touch works.
Now we're curios if it still works on your apollo TCM devices. :)

Installation Instructions:
```
fastboot flash boot boot.img
fastboot flash vendor vendor.img
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
```
The other files must be from the xda sonyaosp build.

**Comment by Sputnik2a** [comment]
Yeeees it rocks :sunglasses:

@MartinX3 & @MarijnS95 - You make may day

[debug_apollo_v8.zip](https://github.com/sonyxperiadev/bug_tracker/files/3587121/debug_apollo_v8.zip)

**Comment by MarijnS95** [comment]
@Sputnik2a Neat, the panel detection works! (meaning I didn't make stupid typos)

Time for a *DONOTMERGE* pull-request, this still needs some cleanup.

**Comment by lapineige** [comment]
That's great :)

I noticed another thing, the geolocation doesn't work (I can activate it, GPS Test app detect some satellites, but I have no location). I guess it's not related ?

**Comment by lapineige** [comment]
Btw, as custom TWRP have the same issue right now, do I need to use the custom one to root my device ? Can I use the stock one (which doesn't have this issue) ?

**Comment by MartinX3** [comment]
Ummhhh
I forgot the twrp.
It simply doesn't contain our fixes for tcm.
I look if I can do something for you in my vacation.

Stock and SODP aren't compatible.

**Comment by lapineige** [comment]
> It simply doesn't contain our fixes for tcm.

That's what I understood, thanks for the confirmation.

It happens ^^ - I also just realized it.
There's no problem, take your time to enjoy your vacation ;)

**Comment by MartinX3** [comment]
Hey @lapineige & @Sputnik2a 
I made a debugging twrp tcm touch fix build with the august security patch level.

http://www.dhsfileserver.de/ftp/MartinX3/Test%20Builds/SODP/Xperia%20XZ2%20Compact/Touch%20Issues/apollo_v8.zip
http://www.dhsfileserver.de/ftp/MartinX3/Test%20Builds/SODP/Xperia%20XZ2%20Compact/Touch%20Issues/2019-09-08_21-18-31_twrp_sodp_xz2c_tcm_touch_fix.tar.gz

Installation Instructions:
```
fastboot flash boot boot.img
fastboot flash vendor vendor.img
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
```
The other files must be from the xda sonyaosp build.

For TWRP just follow the thread instructions.

Hoping it just works, fast hacked as it is. :)
If it doesn't work, we sadly need to wait for a merged PR and my new ROM/TWRP releases on XDA. :)

**Comment by lapineige** [comment]
@MartinX3 you're amazing !

I'm using OmniROM right now, so yeah, it's compatible :D

We need to flash all those all those files, then TWRP ?

**Comment by MartinX3** [comment]
@lapineige 
Nice to hear :)
I hope the vendor.img is compatible, too. :)
And don't forget to apply the vbmeta.img :)

If the vendor.img makes problems, I'll compile a new one for you and upload it for omnirom. :D

**Comment by lapineige** [comment]
> I hope the vendor.img is compatible, too. :)

What do you mean ?

Today I flashed everything from apollo_v8, then OmniROM files, it worked.

**Comment by MartinX3** [comment]
Everything worked? :tada: Nice. That's perfect.
So OmniROM and TWRP have touch?

**Comment by lapineige** [comment]
No I mean I was using OmniROM, then I tested TWRP to root the device. I didn't work, so I came here to tell you.

I'll try TWRP.
I can try just to flash TWRP without changing anything else ?

**Comment by MartinX3** [comment]
Just flash omnirom, then the apollo_v8 files.
Look if the system boots fine.
Then you can use the linked twrp test build by just following the twrp instructions. :)
https://forum.xda-developers.com/xperia-xz2/development/recovery-twrp-3-2-2-0-touch-recovery-t3821597

**Comment by lapineige** [comment]
Ok, so right now I already did flash OmniROM and Apollo_v8 a few hours ago, I'll try the TWRP build :)

**Comment by lapineige** [comment]
No touch.
Here is the log (dmesg): https://vps.lapineige.fr/privatebin/?f48c2b1f68015d60#V/LC/STgvLP9/FpH4p7jc/Y6vIlPO46SoN+u/ArGE+A=

**Comment by MartinX3** [comment]
Thank you, it was my fault.
Somehow the merged kernel commits disappeared while building.
Maybe I did miss something in my build system.

**Comment by MartinX3** [comment]
Found the issue.
In omnirom lunching the device results in a hard git reset on several repositories including the kernel repository.

Now I just lunched, cherry-picked and built.

Use the linked twrp test build by just following the twrp instructions. :)
TWRP:
http://www.dhsfileserver.de/ftp/MartinX3/Test%20Builds/SODP/Xperia%20XZ2%20Compact/Touch%20Issues/apollo_twrp_v8.zip
Instructions:
https://forum.xda-developers.com/xperia-xz2/development/recovery-twrp-3-2-2-0-touch-recovery-t3821597

**Comment by lapineige** [comment]
Touch works ! :tada:
Thanks a lot !

**Comment by MartinX3** [comment]
Wooohooo, nice to hear!

**Comment by lapineige** [comment]
> I noticed another thing, the geolocation doesn't work (I can activate it, GPS Test app detect some satellites, tag them as visible but not used for geolocalisation, but I have no location). I guess it's not related ?

Should I open another issue for this ?

**Comment by MartinX3** [comment]
@lapineige 
Yes please :)

And are you sure the initial gps info gathering just takes its time?
It was the case at my side.
First time it took a bit and the following GPS initializations are instant.

**Comment by lapineige** [comment]
First time I tried during >5 min without any success, but now it worked after 2 min... well, another problem solved ^^

**Comment by Sputnik2a** [comment]
The fix has a regression on my system.

With twrp boot image from apollo_twrp_v8.zip as well as the regular boot image from apollo_v8.zip system does reboot shortly ~10s after the screen goes off if no USB cable to PC is connected. Regardless if the screen goes off automatically or switched off via HW key. With connected USB cable to PC I can switch the screen on/off via HW-Key and timeout/sleep without any regression.

This occur with omnirom as well as with aosp. If the system is booted to TWRP via fastboot as well as installed as Ramdisk no regression occurs.

Test cases:

```
Bootimage         | USB-Cable              | Result
-----------------------------------------------------
With touch fix    | Disconnected           | reset
With touch fix    | Connected to PC [1]    | no reset
With touch fix    | Connected to recharger | reset
Without touch fix | Disconnected           | no reset
Without touch fix | Connected to PC        | no reset
Without touch fix | Connected to recharger | no reset

[1] Only active debugging session on phone side. No ADB session form PC System are initiated

```
The only way I have found to get the logs from previous runtime session was the android system option to permanently store the logs via logcatd where all goes in one log. So the archive contain no dedicated dmesg and logcat but a little hell from all ;-)


Sadly, because in my previous tests to get the logdata I have every time the debug bridge used I found the regression only now where I have tried to become a running custom ROM.

[logcatd_apollo_v8.zip](https://github.com/sonyxperiadev/bug_tracker/files/3612490/logcatd_apollo_v8.zip)

**Comment by MarijnS95** [comment]
This looks like a more generic problem with the image. I don't see any `RescueParty` logs (yeah, it's the party that leaves you with a device that's booted into recovery, instead of one that's at least half-working :man_facepalming:).

```
09-13 21:57:32.506565  2428  2979 V PhoneInterfaceManager: [PhoneIntfMgr] 2 Phones are shutdown.
09-13 21:57:32.506724  1071  3833 I ShutdownThread: Radio turned off.
--------- switch to system
09-13 21:57:32.506792  1071  3833 D ShutdownTiming: ShutdownRadio took to complete: 2354ms
--------- switch to main
09-13 21:57:32.506824  1071  3833 I ShutdownThread: Radio shutdown complete.
--------- switch to system
09-13 21:57:32.507203  1071  3828 D ShutdownTiming: ShutdownRadios took to complete: 2358ms
09-13 21:57:32.507231  1071  3828 D ShutdownTiming: SystemServerShutdown took to complete: 2690ms
--------- switch to main
09-13 21:57:32.508346  1071  3828 I ShutdownThread: Rebooting, reason: null
09-13 21:57:32.515805  3413  3859 W MessagingApp: canonicalizeMccMnc: invalid mccmnc:null ,null
--------- switch to kernel
09-13 21:57:32.509720     0     0 I init    : Received sys.powerctl='reboot,' from pid: 1071 (system_server)
09-13 21:57:32.509816     0     0 I init    : Clear action queue and start shutdown trigger
09-13 21:57:32.509966     0     0 I init    : processing action (shutdown_done) from (<Builtin Action>:0)
09-13 21:57:32.509983     0     0 I init    : Reboot start, reason: reboot,, rebootTarget:
```

Above this there are also some general phone issues, and I am unsure if it is related.
You should check the logs with USB if they have something from `RescueParty` saying that it has an active USB connection.

**Comment by MartinX3** [comment]
Now just https://github.com/sonyxperiadev/kernel/pull/2076 is left to test

Prebuild (version 10) will come later today

**Comment by Sputnik2a** [comment]
@MartinX3 
With apollo-v10 test binaries it works like a charm. Tested it over the last 24h. Neither on SOAP nor TWRP any reset or other glitch.


[dmesg_apollo-v10.zip](https://github.com/sonyxperiadev/bug_tracker/files/3745209/dmesg_apollo-v10.zip)
