### ISSUE TITLE
[4.14][10.0][TAMA][AKARI] Disconnect connect charging cycle with fast charger

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#541]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.14
**Android version:** 10.0
**Software binaries version:** OEMv3

**Previously working on**
Kernel 4.9 with android 9.0

**Description**
The charging mode activates/deactivates in a loop

**Symptoms**
Using the standard fast charger results in a connecting/disconnecting cycle.
The battery charges slowly in short steps like you would connect and disconnect the charger all the time.

**How to reproduce**
Wait until your akari is empty.
Connect it to the default fast charger.
Look how the device charge but the charging connect/disconnects in a cycle

**Additional context**
**Cleaned logfiles:**
**Logcat** (Reduced the amount of healthd reports as well to a single line every block):
```
[ 1061.516662] PMI: smblib_handle_typec_cc_state_change: TypeC SOURCE_DEFAULT insertion
[ 1061.628223] water_detection soc:somc_water_detection: Connection status is changed to 1
[ 1061.628239] water_detection soc:somc_water_detection: wdet_polling_set: state 0 -> 1
[ 1061.630492] healthd: battery l=60 v=3992 t=23.7 h=2 st=3 c=-1342 fc=3089000 chg=
[ 1062.256917] PMI: smblib_somc_handle_wireless_exclusion: usb_present:1, vbus_reg_en:0, running_status:0
[ 1062.256955] IDTP: idtp9221_psy_set_property: POWER_SUPPLY_PROP_USBIN_VALID=1
[ 1062.257457] IDTP: idtp9221_handle_halt: client:1 halt:1
[ 1062.257612] IDTP: idtp9221_handle_halt_proc: Disable WLC_EN
[ 1062.258169] IDTP: idtp9221_control_enable: 0
[ 1062.267819] healthd: battery l=60 v=3822 t=23.7 h=2 st=4 c=273 fc=3089000 chg=a
[ 1063.520232] water_detection soc:somc_water_detection: wdet_check_negotiation_work: polling_state=1
[ 1063.533407] healthd: battery l=60 v=3867 t=23.7 h=2 st=2 c=-214 fc=3089000 chg=a
[ 1064.041979] PMI: smblib_somc_handle_wireless_exclusion: usb_present:1, vbus_reg_en:0, running_status:0
[ 1064.041990] IDTP: idtp9221_psy_set_property: POWER_SUPPLY_PROP_USBIN_VALID=1
[ 1064.042100] IDTP: idtp9221_handle_halt: client:1 halt:1
[ 1064.042211] IDTP: idtp9221_handle_halt_proc: Disable WLC_EN
[ 1064.042429] IDTP: idtp9221_control_enable: 0
[ 1064.043767] usbpd usbpd0: Type-C Source (default) connected
[ 1064.047121] healthd: battery l=60 v=3867 t=23.7 h=2 st=2 c=-214 fc=3089000 chg=a
[ 1068.728676] PMI: smblib_handle_typec_cc_state_change: TypeC removal
[ 1068.729319] water_detection soc:somc_water_detection: Connection status is changed to 0
[ 1068.729325] water_detection soc:somc_water_detection: wdet_invalid_during_negotiation:
[ 1068.729348] water_detection soc:somc_water_detection: wdet_polling_set: state 1 -> 0
[ 1068.729599] usbpd usbpd0: USB Type-C disconnect
[ 1068.729758] set_prop is inhibited because typec is not present
[ 1068.729849] set_prop is inhibited because typec is not present
[ 1068.729989] set_prop is inhibited because typec is not present
[ 1068.730101] set_prop is inhibited because typec is not present
[ 1068.775544] PMI: smblib_handle_typec_cc_state_change: TypeC SOURCE_DEFAULT insertion
[ 1068.885953] water_detection soc:somc_water_detection: Connection status is changed to 1
[ 1068.885964] water_detection soc:somc_water_detection: wdet_polling_set: state 0 -> 1
[ 1068.888442] healthd: battery l=61 v=3990 t=23.7 h=2 st=3 c=-1319 fc=3089000 chg=
[ 1069.520472] PMI: smblib_somc_handle_wireless_exclusion: usb_present:1, vbus_reg_en:0, running_status:0
[ 1069.520485] IDTP: idtp9221_psy_set_property: POWER_SUPPLY_PROP_USBIN_VALID=1
[ 1069.520636] IDTP: idtp9221_handle_halt: client:1 halt:1
[ 1069.520708] IDTP: idtp9221_handle_halt_proc: Disable WLC_EN
[ 1069.520943] IDTP: idtp9221_control_enable: 0
[ 1069.524547] healthd: battery l=61 v=3805 t=23.7 h=2 st=4 c=420 fc=3089000 chg=a
[ 1070.752186] water_detection soc:somc_water_detection: wdet_check_negotiation_work: polling_state=1
[ 1070.770171] healthd: battery l=61 v=3883 t=23.7 h=2 st=2 c=-379 fc=3089000 chg=a
[ 1071.291197] PMI: smblib_somc_handle_wireless_exclusion: usb_present:1, vbus_reg_en:0, running_status:0
[ 1071.291207] IDTP: idtp9221_psy_set_property: POWER_SUPPLY_PROP_USBIN_VALID=1
[ 1071.291329] IDTP: idtp9221_handle_halt: client:1 halt:1
[ 1071.291389] IDTP: idtp9221_handle_halt_proc: Disable WLC_EN
[ 1071.291601] IDTP: idtp9221_control_enable: 0
[ 1071.292259] usbpd usbpd0: Type-C Source (default) connected
[ 1075.521077] healthd: battery l=61 v=4000 t=23.7 h=2 st=2 c=-1412 fc=3089000 chg=a
[ 1075.968846] PMI: smblib_handle_typec_cc_state_change: TypeC removal
[ 1075.969907] water_detection soc:somc_water_detection: Connection status is changed to 0
[ 1075.969920] water_detection soc:somc_water_detection: wdet_invalid_during_negotiation:
[ 1075.969979] water_detection soc:somc_water_detection: wdet_polling_set: state 1 -> 0
[ 1075.970191] usbpd usbpd0: USB Type-C disconnect
[ 1075.970386] set_prop is inhibited because typec is not present
[ 1075.970590] set_prop is inhibited because typec is not present
[ 1075.970919] set_prop is inhibited because typec is not present
[ 1075.971107] set_prop is inhibited because typec is not present
[ 1076.024778] PMI: smblib_handle_typec_cc_state_change: TypeC SOURCE_DEFAULT insertion
[ 1076.126298] water_detection soc:somc_water_detection: Connection status is changed to 1
[ 1076.127821] healthd: battery l=61 v=4000 t=23.7 h=2 st=3 c=-1412 fc=3089000 chg=
[ 1076.129191] water_detection soc:somc_water_detection: wdet_polling_set: state 0 -> 1
[ 1076.182450] healthd: battery l=61 v=4000 t=23.7 h=2 st=3 c=-1412 fc=3089000 chg=
[ 1076.775568] PMI: smblib_somc_handle_wireless_exclusion: usb_present:1, vbus_reg_en:0, running_status:0
[ 1076.775606] IDTP: idtp9221_psy_set_property: POWER_SUPPLY_PROP_USBIN_VALID=1
[ 1076.775825] IDTP: idtp9221_handle_halt: client:1 halt:1
[ 1076.776302] IDTP: idtp9221_handle_halt_proc: Disable WLC_EN
[ 1076.776709] IDTP: idtp9221_control_enable: 0
[ 1076.783210] healthd: battery l=61 v=3828 t=23.7 h=2 st=4 c=211 fc=3089000 chg=a
[ 1077.984122] water_detection soc:somc_water_detection: wdet_check_negotiation_work: polling_state=1
[ 1078.016823] healthd: battery l=61 v=3872 t=23.7 h=2 st=2 c=-267 fc=3089000 chg=a
[ 1078.540649] PMI: smblib_somc_handle_wireless_exclusion: usb_present:1, vbus_reg_en:0, running_status:0
[ 1078.540667] IDTP: idtp9221_psy_set_property: POWER_SUPPLY_PROP_USBIN_VALID=1
[ 1078.540855] IDTP: idtp9221_handle_halt: client:1 halt:1
[ 1078.540950] IDTP: idtp9221_handle_halt_proc: Disable WLC_EN
[ 1078.541367] IDTP: idtp9221_control_enable: 0
[ 1078.542452] usbpd usbpd0: Type-C Source (default) connected
[ 1078.545826] healthd: battery l=61 v=3872 t=23.7 h=2 st=2 c=-267 fc=3089000 chg=a
[ 1083.217857] PMI: smblib_handle_typec_cc_state_change: TypeC removal
[ 1083.218625] water_detection soc:somc_water_detection: Connection status is changed to 0
[ 1083.218633] water_detection soc:somc_water_detection: wdet_invalid_during_negotiation:
[ 1083.218661] water_detection soc:somc_water_detection: wdet_polling_set: state 1 -> 0
[ 1083.218778] usbpd usbpd0: USB Type-C disconnect
[ 1083.218946] set_prop is inhibited because typec is not present
[ 1083.219089] set_prop is inhibited because typec is not present
[ 1083.219244] set_prop is inhibited because typec is not present
[ 1083.219332] set_prop is inhibited because typec is not present
[ 1083.277457] PMI: smblib_handle_typec_cc_state_change: TypeC SOURCE_DEFAULT insertion
[ 1083.374758] water_detection soc:somc_water_detection: Connection status is changed to 1
[ 1083.374769] water_detection soc:somc_water_detection: wdet_polling_set: state 0 -> 1
[ 1083.376901] healthd: battery l=61 v=3991 t=23.7 h=2 st=3 c=-1322 fc=3089000 chg=
[ 1084.019687] PMI: smblib_somc_handle_wireless_exclusion: usb_present:1, vbus_reg_en:0, running_status:0
[ 1084.019704] IDTP: idtp9221_psy_set_property: POWER_SUPPLY_PROP_USBIN_VALID=1
[ 1084.019817] IDTP: idtp9221_handle_halt: client:1 halt:1
[ 1084.019975] IDTP: idtp9221_handle_halt_proc: Disable WLC_EN
[ 1084.020328] IDTP: idtp9221_control_enable: 0
[ 1084.024834] healthd: battery l=61 v=3815 t=23.7 h=2 st=4 c=322 fc=3089000 chg=a
[ 1085.280082] water_detection soc:somc_water_detection: wdet_check_negotiation_work: polling_state=1
[ 1085.301144] healthd: battery l=61 v=3880 t=23.7 h=2 st=2 c=-338 fc=3089000 chg=a
[ 1085.789841] PMI: smblib_somc_handle_wireless_exclusion: usb_present:1, vbus_reg_en:0, running_status:0
[ 1085.789852] IDTP: idtp9221_psy_set_property: POWER_SUPPLY_PROP_USBIN_VALID=1
[ 1085.789985] IDTP: idtp9221_handle_halt: client:1 halt:1
[ 1085.790099] IDTP: idtp9221_handle_halt_proc: Disable WLC_EN
[ 1085.790392] IDTP: idtp9221_control_enable: 0
[ 1085.791012] usbpd usbpd0: Type-C Source (default) connected
[ 1085.797344] healthd: battery l=61 v=3880 t=23.7 h=2 st=2 c=-338 fc=3089000 chg=a
[ 1090.464547] PMI: smblib_handle_typec_cc_state_change: TypeC removal
[ 1090.465225] water_detection soc:somc_water_detection: Connection status is changed to 0
[ 1090.465232] water_detection soc:somc_water_detection: wdet_invalid_during_negotiation:
[ 1090.465262] water_detection soc:somc_water_detection: wdet_polling_set: state 1 -> 0
[ 1090.465365] usbpd usbpd0: USB Type-C disconnect
[ 1090.465530] set_prop is inhibited because typec is not present
[ 1090.465698] set_prop is inhibited because typec is not present
[ 1090.465908] set_prop is inhibited because typec is not present
[ 1090.466138] set_prop is inhibited because typec is not present
[ 1090.513799] PMI: smblib_handle_typec_cc_state_change: TypeC SOURCE_DEFAULT insertion
[ 1090.619394] water_detection soc:somc_water_detection: Connection status is changed to 1
[ 1090.619408] water_detection soc:somc_water_detection: wdet_polling_set: state 0 -> 1
[ 1090.723597] healthd: battery l=61 v=3996 t=23.7 h=2 st=3 c=-1382 fc=3089000 chg=
[ 1091.248374] PMI: smblib_somc_handle_wireless_exclusion: usb_present:1, vbus_reg_en:0, running_status:0
[ 1091.248391] IDTP: idtp9221_psy_set_property: POWER_SUPPLY_PROP_USBIN_VALID=1
[ 1091.248551] IDTP: idtp9221_handle_halt: client:1 halt:1
[ 1091.248630] IDTP: idtp9221_handle_halt_proc: Disable WLC_EN
[ 1091.248974] IDTP: idtp9221_control_enable: 0
[ 1091.253851] healthd: battery l=61 v=3816 t=23.7 h=2 st=4 c=321 fc=3089000 chg=a
[ 1092.512158] water_detection soc:somc_water_detection: wdet_check_negotiation_work: polling_state=1
[ 1092.530228] healthd: battery l=61 v=3892 t=23.7 h=2 st=2 c=-458 fc=3089000 chg=a
[ 1093.039477] PMI: smblib_somc_handle_wireless_exclusion: usb_present:1, vbus_reg_en:0, running_status:0
[ 1093.039489] IDTP: idtp9221_psy_set_property: POWER_SUPPLY_PROP_USBIN_VALID=1
[ 1093.039615] IDTP: idtp9221_handle_halt: client:1 halt:1
[ 1093.039678] IDTP: idtp9221_handle_halt_proc: Disable WLC_EN
[ 1093.039900] IDTP: idtp9221_control_enable: 0
[ 1093.040591] usbpd usbpd0: Type-C Source (default) connected
[ 1093.047281] healthd: battery l=61 v=3892 t=23.7 h=2 st=2 c=-458 fc=3089000 chg=a
[ 1097.712590] PMI: smblib_handle_typec_cc_state_change: TypeC removal
[ 1097.713354] water_detection soc:somc_water_detection: Connection status is changed to 0
[ 1097.713366] water_detection soc:somc_water_detection: wdet_invalid_during_negotiation:
[ 1097.713404] water_detection soc:somc_water_detection: wdet_polling_set: state 1 -> 0
[ 1097.713518] usbpd usbpd0: USB Type-C disconnect
[ 1097.713702] set_prop is inhibited because typec is not present
[ 1097.713887] set_prop is inhibited because typec is not present
[ 1097.713974] set_prop is inhibited because typec is not present
[ 1097.714185] set_prop is inhibited because typec is not present
[ 1097.766061] PMI: smblib_handle_typec_cc_state_change: TypeC SOURCE_DEFAULT insertion
[ 1097.819983] water_detection soc:somc_water_detection: Connection status is changed to 1
[ 1097.820010] water_detection soc:somc_water_detection: wdet_polling_set: state 0 -> 1
[ 1097.924577] healthd: battery l=61 v=4005 t=24.0 h=2 st=3 c=-1452 fc=3089000 chg=
[ 1098.497682] PMI: smblib_somc_handle_wireless_exclusion: usb_present:1, vbus_reg_en:0, running_status:0
[ 1098.497717] IDTP: idtp9221_psy_set_property: POWER_SUPPLY_PROP_USBIN_VALID=1
[ 1098.498167] IDTP: idtp9221_handle_halt: client:1 halt:1
[ 1098.498322] IDTP: idtp9221_handle_halt_proc: Disable WLC_EN
[ 1098.498854] IDTP: idtp9221_control_enable: 0
[ 1098.504500] healthd: battery l=61 v=3834 t=24.0 h=2 st=4 c=134 fc=3089000 chg=a
[ 1099.744093] water_detection soc:somc_water_detection: wdet_check_negotiation_work: polling_state=1
[ 1099.746542] healthd: battery l=61 v=3834 t=23.7 h=2 st=2 c=134 fc=3089000 chg=a
[ 1100.288605] PMI: smblib_somc_handle_wireless_exclusion: usb_present:1, vbus_reg_en:0, running_status:0
[ 1100.288618] IDTP: idtp9221_psy_set_property: POWER_SUPPLY_PROP_USBIN_VALID=1
[ 1100.288709] IDTP: idtp9221_handle_halt: client:1 halt:1
[ 1100.288852] IDTP: idtp9221_handle_halt_proc: Disable WLC_EN
[ 1100.289171] IDTP: idtp9221_control_enable: 0
[ 1100.289909] usbpd usbpd0: Type-C Source (default) connected
[ 1100.296014] healthd: battery l=61 v=3893 t=23.7 h=2 st=2 c=-461 fc=3089000 chg=a
```

**Dmesg:**
```
02-19 08:10:27.161   656  1499 E android.hardware.usb@1.0-service: uevent received SUBSYSTEM=dual_role_usb
02-19 08:10:27.162   656  1499 I android.hardware.usb@1.0-service: otg_default
02-19 08:10:27.163   656  1499 I android.hardware.usb@1.0-service: canChangeMode: 0 canChagedata: 0 canChangePower:0
02-19 08:10:27.167   932  1005 I UsbPortManager: ClientCallback V1_0: otg_default
02-19 08:10:27.168   932   968 I UsbPortManager: USB port changed: port=UsbPort{id=otg_default, supportedModes=dualsupportedContaminantProtectionModes=0supportsEnableContaminantPresenceProtection=falsesupportsEnableContaminantPresenceDetection=false, status=UsbPortStatus{connected=true, currentMode=ufp, currentPowerRole=sink, currentDataRole=device, supportedRoleCombinations=[sink:device], contaminantDetectionStatus=0, contaminantProtectionStatus=0}, canChangeMode=false, canChangePowerRole=false, canChangeDataRole=false, connectedAtMillis=1107545, lastConnectDurationMillis=0
02-19 08:10:28.348   656  1499 E android.hardware.usb@1.0-service: uevent received SUBSYSTEM=dual_role_usb
02-19 08:10:28.349   656  1499 I android.hardware.usb@1.0-service: otg_default
02-19 08:10:28.349   656  1499 I android.hardware.usb@1.0-service: canChangeMode: 0 canChagedata: 0 canChangePower:0
02-19 08:10:28.353   932  1005 I UsbPortManager: ClientCallback V1_0: otg_default
02-19 08:10:29.543   656  1499 E android.hardware.usb@1.0-service: uevent received SUBSYSTEM=dual_role_usb
02-19 08:10:29.544   656  1499 I android.hardware.usb@1.0-service: otg_default
02-19 08:10:29.545   656  1499 I android.hardware.usb@1.0-service: canChangeMode: 0 canChagedata: 0 canChangePower:0
02-19 08:10:30.731   656  1499 E android.hardware.usb@1.0-service: uevent received SUBSYSTEM=dual_role_usb
02-19 08:10:30.731   656  1499 I android.hardware.usb@1.0-service: otg_default
02-19 08:10:30.732   656  1499 I android.hardware.usb@1.0-service: canChangeMode: 0 canChagedata: 0 canChangePower:0
02-19 08:10:31.853   656  1499 E android.hardware.usb@1.0-service: uevent received SUBSYSTEM=dual_role_usb
02-19 08:10:31.853   656  1499 I android.hardware.usb@1.0-service: otg_default
02-19 08:10:31.854   656  1499 I android.hardware.usb@1.0-service: canChangeMode: 0 canChagedata: 0 canChangePower:0
02-19 08:10:30.732   932  1005 I chatty  : uid=1000(system) HwBinder:932_1 identical 2 lines
02-19 08:10:31.854   932  1005 I UsbPortManager: ClientCallback V1_0: otg_default
02-19 08:10:31.855   932   968 I UsbPortManager: USB port changed: port=UsbPort{id=otg_default, supportedModes=dualsupportedContaminantProtectionModes=0supportsEnableContaminantPresenceProtection=falsesupportsEnableContaminantPresenceDetection=false, status=UsbPortStatus{connected=false, currentMode=none, currentPowerRole=no-power, currentDataRole=no-data, supportedRoleCombinations=[no-power:no-data], contaminantDetectionStatus=0, contaminantProtectionStatus=0}, canChangeMode=false, canChangePowerRole=false, canChangeDataRole=false, connectedAtMillis=0, lastConnectDurationMillis=4687
02-19 08:10:32.009   932   977 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_DISCONNECTED flg=0x4000010 (has extras) } to com.google.android.apps.turbo/.nudges.broadcasts.BatteryStatusChangedReceiver
02-19 08:10:32.009   932   977 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_DISCONNECTED flg=0x4000010 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
02-19 08:10:32.009   932   977 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_DISCONNECTED flg=0x4000010 (has extras) } to com.linecorp.linelite/.app.module.android.system.SystemBroadcastReceiver
02-19 08:10:32.025   932   984 E BatteryExternalStatsWorker: no controller energy info supplied for bluetooth
02-19 08:10:32.043   932   984 E KernelWakelockReader: Failed to parse proc line: IPA_RM14
02-19 08:10:32.044   932   984 E KernelWakelockReader: Failed to parse proc line: IPA_RM12
02-19 08:10:32.044   932   977 I DropBoxManagerService: add tag=system_server_wtf isTagEnabled=true flags=0x2
02-19 08:10:32.650   932   977 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_CONNECTED flg=0x4000010 (has extras) } to com.google.android.apps.turbo/.nudges.broadcasts.BatteryStatusChangedReceiver
02-19 08:10:32.650   932   977 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_CONNECTED flg=0x4000010 (has extras) } to com.google.android.gms/.gcm.nts.SchedulerReceiver
02-19 08:10:32.650   932   977 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_CONNECTED flg=0x4000010 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
02-19 08:10:32.650   932   977 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_CONNECTED flg=0x4000010 (has extras) } to com.linecorp.linelite/.app.module.android.system.SystemBroadcastReceiver
02-19 08:10:32.668   932   984 E BatteryExternalStatsWorker: no controller energy info supplied for bluetooth
02-19 08:10:32.699   932   984 E KernelWakelockReader: Failed to parse proc line: IPA_RM14
02-19 08:10:32.701   932   984 E KernelWakelockReader: Failed to parse proc line: IPA_RM12
02-19 08:10:32.701   932   977 I DropBoxManagerService: add tag=system_server_wtf isTagEnabled=true flags=0x2
02-19 08:10:32.718   622  6726 I netd    : trafficSwapActiveStatsMap() <13.94ms>
02-19 08:10:32.721   622  6726 I netd    : tetherGetStats() <1.49ms>
02-19 08:10:32.733   622  6726 I netd    : trafficSwapActiveStatsMap() <0.24ms>
02-19 08:10:32.735   622  6726 I netd    : tetherGetStats() <1.15ms>
02-19 08:10:34.408   656  1499 E android.hardware.usb@1.0-service: uevent received SUBSYSTEM=dual_role_usb
02-19 08:10:34.408   656  1499 I android.hardware.usb@1.0-service: otg_default
02-19 08:10:34.409   656  1499 I android.hardware.usb@1.0-service: canChangeMode: 0 canChagedata: 0 canChangePower:0
02-19 08:10:34.410   932  1005 I UsbPortManager: ClientCallback V1_0: otg_default
02-19 08:10:34.412   932   968 I UsbPortManager: USB port changed: port=UsbPort{id=otg_default, supportedModes=dualsupportedContaminantProtectionModes=0supportsEnableContaminantPresenceProtection=falsesupportsEnableContaminantPresenceDetection=false, status=UsbPortStatus{connected=true, currentMode=ufp, currentPowerRole=sink, currentDataRole=device, supportedRoleCombinations=[sink:device], contaminantDetectionStatus=0, contaminantProtectionStatus=0}, canChangeMode=false, canChangePowerRole=false, canChangeDataRole=false, connectedAtMillis=1114789, lastConnectDurationMillis=0
02-19 08:10:35.595   656  1499 E android.hardware.usb@1.0-service: uevent received SUBSYSTEM=dual_role_usb
02-19 08:10:35.596   656  1499 I android.hardware.usb@1.0-service: otg_default
02-19 08:10:35.597   656  1499 I android.hardware.usb@1.0-service: canChangeMode: 0 canChagedata: 0 canChangePower:0
02-19 08:10:35.598   932  1005 I UsbPortManager: ClientCallback V1_0: otg_default
02-19 08:10:36.785   656  1499 E android.hardware.usb@1.0-service: uevent received SUBSYSTEM=dual_role_usb
02-19 08:10:36.785   656  1499 I android.hardware.usb@1.0-service: otg_default
02-19 08:10:36.786   656  1499 I android.hardware.usb@1.0-service: canChangeMode: 0 canChagedata: 0 canChangePower:0
02-19 08:10:37.980   656  1499 E android.hardware.usb@1.0-service: uevent received SUBSYSTEM=dual_role_usb
02-19 08:10:37.981   656  1499 I android.hardware.usb@1.0-service: otg_default
02-19 08:10:37.982   656  1499 I android.hardware.usb@1.0-service: canChangeMode: 0 canChagedata: 0 canChangePower:0
02-19 08:10:39.103   656  1499 E android.hardware.usb@1.0-service: uevent received SUBSYSTEM=dual_role_usb
02-19 08:10:39.104   656  1499 I android.hardware.usb@1.0-service: otg_default
02-19 08:10:39.104   656  1499 I android.hardware.usb@1.0-service: canChangeMode: 0 canChagedata: 0 canChangePower:0
02-19 08:10:37.984   932  1005 I chatty  : uid=1000(system) HwBinder:932_1 identical 2 lines
02-19 08:10:39.106   932  1005 I UsbPortManager: ClientCallback V1_0: otg_default
02-19 08:10:39.106   932   968 I UsbPortManager: USB port changed: port=UsbPort{id=otg_default, supportedModes=dualsupportedContaminantProtectionModes=0supportsEnableContaminantPresenceProtection=falsesupportsEnableContaminantPresenceDetection=false, status=UsbPortStatus{connected=false, currentMode=none, currentPowerRole=no-power, currentDataRole=no-data, supportedRoleCombinations=[no-power:no-data], contaminantDetectionStatus=0, contaminantProtectionStatus=0}, canChangeMode=false, canChangePowerRole=false, canChangeDataRole=false, connectedAtMillis=0, lastConnectDurationMillis=4695
02-19 08:10:39.221   932   977 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_DISCONNECTED flg=0x4000010 (has extras) } to com.google.android.apps.turbo/.nudges.broadcasts.BatteryStatusChangedReceiver
02-19 08:10:39.221   932   977 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_DISCONNECTED flg=0x4000010 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
02-19 08:10:39.222   932   977 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_DISCONNECTED flg=0x4000010 (has extras) } to com.linecorp.linelite/.app.module.android.system.SystemBroadcastReceiver
02-19 08:10:39.239   932   984 E BatteryExternalStatsWorker: no controller energy info supplied for bluetooth
02-19 08:10:41.662   656  1499 E android.hardware.usb@1.0-service: uevent received SUBSYSTEM=dual_role_usb
02-19 08:10:41.662   656  1499 I android.hardware.usb@1.0-service: otg_default
02-19 08:10:41.664   656  1499 I android.hardware.usb@1.0-service: canChangeMode: 0 canChagedata: 0 canChangePower:0
02-19 08:10:41.664   932  1005 I UsbPortManager: ClientCallback V1_0: otg_default
02-19 08:10:41.665   932   968 I UsbPortManager: USB port changed: port=UsbPort{id=otg_default, supportedModes=dualsupportedContaminantProtectionModes=0supportsEnableContaminantPresenceProtection=falsesupportsEnableContaminantPresenceDetection=false, status=UsbPortStatus{connected=true, currentMode=ufp, currentPowerRole=sink, currentDataRole=device, supportedRoleCombinations=[sink:device], contaminantDetectionStatus=0, contaminantProtectionStatus=0}, canChangeMode=false, canChangePowerRole=false, canChangeDataRole=false, connectedAtMillis=1122042, lastConnectDurationMillis=0
02-19 08:10:42.842   656  1499 E android.hardware.usb@1.0-service: uevent received SUBSYSTEM=dual_role_usb
02-19 08:10:42.842   656  1499 I android.hardware.usb@1.0-service: otg_default
02-19 08:10:42.842   656  1499 I android.hardware.usb@1.0-service: canChangeMode: 0 canChagedata: 0 canChangePower:0
02-19 08:10:42.843   932  1005 I UsbPortManager: ClientCallback V1_0: otg_default
02-19 08:10:44.028   656  1499 E android.hardware.usb@1.0-service: uevent received SUBSYSTEM=dual_role_usb
02-19 08:10:44.028   656  1499 I android.hardware.usb@1.0-service: otg_default
02-19 08:10:44.029   656  1499 I android.hardware.usb@1.0-service: canChangeMode: 0 canChagedata: 0 canChangePower:0
02-19 08:10:44.031   932  1005 I UsbPortManager: ClientCallback V1_0: otg_default
02-19 08:10:45.176   932   972 E system_server: Invalid ID 0x00000000.
02-19 08:10:45.214   656  1499 E android.hardware.usb@1.0-service: uevent received SUBSYSTEM=dual_role_usb
02-19 08:10:45.214   656  1499 I android.hardware.usb@1.0-service: otg_default
02-19 08:10:45.215   656  1499 I android.hardware.usb@1.0-service: canChangeMode: 0 canChagedata: 0 canChangePower:0
02-19 08:10:45.216   932  1005 I UsbPortManager: ClientCallback V1_0: otg_default
02-19 08:10:45.345   932   984 E BatteryExternalStatsWorker: no controller energy info supplied for bluetooth
02-19 08:10:45.347  9180 11936 D SettingsActivity: No enabled state changed, skipping updateCategory call
02-19 08:10:45.362   932   984 E KernelWakelockReader: Failed to parse proc line: IPA_RM14
02-19 08:10:45.363   932   984 E KernelWakelockReader: Failed to parse proc line: IPA_RM12
02-19 08:10:45.363   932   977 I DropBoxManagerService: add tag=system_server_wtf isTagEnabled=true flags=0x2
02-19 08:10:45.372   932   977 I DropBoxManagerService: add tag=system_server_wtf isTagEnabled=true flags=0x2
02-19 08:10:46.333   656  1499 E android.hardware.usb@1.0-service: uevent received SUBSYSTEM=dual_role_usb
02-19 08:10:46.333   656  1499 I android.hardware.usb@1.0-service: otg_default
02-19 08:10:46.334   656  1499 I android.hardware.usb@1.0-service: canChangeMode: 0 canChagedata: 0 canChangePower:0
02-19 08:10:46.335   932  1005 I UsbPortManager: ClientCallback V1_0: otg_default
02-19 08:10:46.335   932   968 I UsbPortManager: USB port changed: port=UsbPort{id=otg_default, supportedModes=dualsupportedContaminantProtectionModes=0supportsEnableContaminantPresenceProtection=falsesupportsEnableContaminantPresenceDetection=false, status=UsbPortStatus{connected=false, currentMode=none, currentPowerRole=no-power, currentDataRole=no-data, supportedRoleCombinations=[no-power:no-data], contaminantDetectionStatus=0, contaminantProtectionStatus=0}, canChangeMode=false, canChangePowerRole=false, canChangeDataRole=false, connectedAtMillis=0, lastConnectDurationMillis=4671
02-19 08:10:46.492   932   977 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_DISCONNECTED flg=0x4000010 (has extras) } to com.google.android.apps.turbo/.nudges.broadcasts.BatteryStatusChangedReceiver
02-19 08:10:46.492   932   977 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_DISCONNECTED flg=0x4000010 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
02-19 08:10:46.492   932   977 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_DISCONNECTED flg=0x4000010 (has extras) } to com.linecorp.linelite/.app.module.android.system.SystemBroadcastReceiver
02-19 08:10:46.506   932   984 E BatteryExternalStatsWorker: no controller energy info supplied for bluetooth
02-19 08:10:46.525   932   984 E KernelWakelockReader: Failed to parse proc line: IPA_RM14
02-19 08:10:46.526   932   984 E KernelWakelockReader: Failed to parse proc line: IPA_RM12
02-19 08:10:46.535   932   977 I DropBoxManagerService: add tag=system_server_wtf isTagEnabled=true flags=0x2
02-19 08:10:47.120   932   977 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_CONNECTED flg=0x4000010 (has extras) } to com.google.android.apps.turbo/.nudges.broadcasts.BatteryStatusChangedReceiver
02-19 08:10:47.120   932   977 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_CONNECTED flg=0x4000010 (has extras) } to com.google.android.gms/.gcm.nts.SchedulerReceiver
02-19 08:10:47.120   932   977 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_CONNECTED flg=0x4000010 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
02-19 08:10:47.121   932   977 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_CONNECTED flg=0x4000010 (has extras) } to com.linecorp.linelite/.app.module.android.system.SystemBroadcastReceiver
02-19 08:10:47.141   932   984 E BatteryExternalStatsWorker: no controller energy info supplied for bluetooth
02-19 08:10:47.158   932   984 E KernelWakelockReader: Failed to parse proc line: IPA_RM14
02-19 08:10:47.159   932   984 E KernelWakelockReader: Failed to parse proc line: IPA_RM12
02-19 08:10:47.159   932   977 I DropBoxManagerService: add tag=system_server_wtf isTagEnabled=true flags=0x2
```

Uncleaned logfiles are here:
https://github.com/MartinX3-AndroidDevelopment-LineageOS/bug_tracker/issues/11

**Comment by Paulbouchara** [comment]
Qualcomm Fast Chargers aren't supported, this is because the charger tries to ramp up the voltage and fails because either the kernel or the missing blob didn't sent the right command

**Comment by MartinX3** [comment]
The official Sony fast charger delivered together with my phone won't be supported?
It did work in 4.9.

**Comment by nos1609** [comment]
Stabilized for me after a deadlock discharge, fixed with vol-up+power+camera combo. Now quick charge works as expected on OEMv3.

**Comment by nickholtus** [comment]
Same issue on XZ3, V4 doesn't fix it

**Comment by MartinX3** [comment]
Updated my kernel to commit https://github.com/sonyxperiadev/kernel/commit/1aaf380ed91b99fd8816a6924fc083ccba43d446
Still broken with the default sony xz2 charger
[logcat-ball.log](https://github.com/sonyxperiadev/bug_tracker/files/4690271/logcat-ball.log)

**Comment by MartinX3** [comment]
Updated my kernel to https://github.com/sonyxperiadev/kernel/pull/2273
QuickCharge 3 is still broken on my XZ2.

[ChargerIssues.log](https://github.com/sonyxperiadev/bug_tracker/files/4707689/ChargerIssues.log)

**Comment by kholk** [comment]
This issue has been solved with https://github.com/sonyxperiadev/kernel/pull/2280

Please confirm and close this issue.

**Comment by MartinX3** [comment]
Thanks for reminding.
It's fixed.
