### ISSUE TITLE
[Seine][pdx201] No sound at all from device.

### ISSUE THREAD

**Issue by AngryGami** [sonyxperiadev/bug_tracker#617]
**Platform:** Seine
**Device:** pdx201
**Kernel version:** 4.14
**Android version:** 10
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v9c_seine

**Previously working on**
Can't tell. 

**Description**
No sound whatsoever comes from device.

**Symptoms**
```
2020-07-15 22:17:07.961 710-4716/? E/audio_hw_sony_cirrus_playback: cirrus_get_mixer_array_by_name: Cannot get mixer control DSP1 Protection cd CSPL_ERRORNO
2020-07-15 22:17:07.963 710-4716/? E/audio_hw_sony_cirrus_playback: cirrus_check_error_state_mono: Cannot get CSPL status
2020-07-15 22:17:07.965 710-4619/? E/ACDB-LOADER: ACDB get afe topology for acdb id = 124, err = -8
2020-07-15 22:17:07.965 710-4619/? E/ACDB-LOADER: Error: get ACDB afe topology result = -8
2020-07-15 22:17:07.967 710-4619/? E/ACDB-LOADER: Error: ACDB_CMD_GET_AFE_INSTANCE_COMMON_TABLE_SIZE Returned = -20
2020-07-15 22:17:07.968 710-4619/? E/ACDB-LOADER: Error: ACDB AFE returned = -20
2020-07-15 22:17:07.970 710-4619/? E/ACDB-LOADER: Error: ACDB ACDB_CMD_GET_DEVICE_PROPERTY error = -1
2020-07-15 22:17:08.004 710-4619/? E/audio_hw_primary: pcm_open_prepare_helper: pcm_prepare returned -1
2020-07-15 22:17:08.043 710-4619/? E/soundtrigger: audio_extn_sound_trigger_update_stream_status: invalid input device 0x0, for event 2
2020-07-15 22:17:08.121 710-3575/? E/msm8974_platform: platform_check_backends_match: Invalid snd_device = 
2020-07-15 22:17:08.127 710-3575/? E/soundtrigger: audio_extn_sound_trigger_update_stream_status: invalid input device 0x0, for event 3
2020-07-15 22:17:08.135 710-3575/? E/ACDB-LOADER: Error: ACDB get adm topology for acdb id = 124, returned = -8
2020-07-15 22:17:08.137 710-3575/? E/ACDB-LOADER: Error: ACDB_CMD_GET_AUDPROC_INSTANCE_COMMON_TABLE_SIZE Returned = -20
2020-07-15 22:17:08.138 710-3575/? E/ACDB-LOADER: Error: ACDB audproc returned = -20
2020-07-15 22:17:08.140 710-3575/? E/ACDB-LOADER: Error: ACDB_CMD_GET_AUDPROC_INSTANCE_GAIN_DEP_STEP_TABLE_SIZE Returned = -20
```

**How to reproduce**
Flash aosp image build from repo at branch `android-10.0.0_r40`

**Comment by MarijnS95** [comment]
We're definitely fully aware of this problem and mentally working on a fix. No time to type it in though.

**Comment by AngryGami** [comment]
Is this a duplicate of some other issue?

**Comment by kholk** [comment]
You can fix it by adding system group to the audio hal's init rc. We are trying to find a way to fix this properly.

**Comment by AngryGami** [comment]
I'm only vaguely understand your suggestion. Which of over hundred init rc files you are talking about? Is this at all related to rc files or maybe this is some other hal related low level stuff?

**Comment by MarijnS95** [comment]
@AngryGami The Cirrus issue is fixed, but sepolicy is still pending until I can physically validate my own device.

Then @paulbouchara doesn't seem to get any sound while I did (when Cirrus is ignored), be it with a different audio policy. That, also, is a change already in the pipeline but needs validation now that Cirrus is fixed. Expect a PR for that soon, too.

**Comment by MarijnS95** [comment]
@AngryGami I hope you don't mind I auto-closed this issue with GitHubs `Closes #...` feature, unsurprisingly our audio policy and paths are not ready yet. I've only been able to really quickly test an initial set of rules prepared about a month ago, which give compressed audio playback but low latency (system sounds) are broken. Nothing else was tested yet, expect a working configuration in a couple days.

**Comment by AngryGami** [comment]
I don't mind having this closed.... though in my build from latest source sound still doesn't work at all. Maybe I can track other issue that eventually have solution for this problem?

**Comment by MarijnS95** [comment]
I'll ping this issue as soon as a solution arrives...

FWIW we pretty much have one at this point, revert https://github.com/sonyxperiadev/device-sony-pdx201/commit/f58e3ae0f49b99bc1117540321034e8aefb5bcab

We're still breaking our heads (not only because of a heatwave) over why this works for Angelo, but not for me. The kernel shows that it fails to open some ports and initialize the backend on `RX_CDC_DMA_RX_0`, which kindof makes sense while it also doesn't.
We'll keep digging and eventually find a solution.

Do note that I haven't fully tested audio after that yet! Deep buffer and low latency playback over speakers started working in addition to compressed offload, but I wasn't able to get to the rest (wired headphones and handset, during (voip) calls, audio recording, etc etc etc).

**Comment by MarijnS95** [comment]
@AngryGami Also, if you feel like helping with such a test we'd be largely grateful. There are many devices (speakers, handset, wired headphones, wired headset, bluetooth headphones/set, usb headphones/set), and a lot of usecases (the way audio is played back such as calls, voip calls, (ultra) low latency in games and system sounds, compressed offload for hardware decoding of some media formats, deep buffer playback for the more exotic media formats decoded in software, and the list goes on), not to mention microphone/recording action.

Take the Cartesian product of devices and usecases and you see how massive this test becomes... Which needs to be conducted on every device. Just seeing if audio works isn't enough, we have to validate logs for every case that the expected paths are taken.

If your time allows we'd love to see some detailed feedback on the audio situation on PDX201. Try playing back various media files 
and send us the log snippet (a single annotated log might be best), include `ffprobe` info too so we can see the exact media format, bitrates etc. Place calls, use a voip app, record some audio, and play some games. In calls, don't forget to switch between speaker and handset, make sure volume changes work. And use speakers, wired headset and bluetooth headset :)

If not, that's fine too but a full test sweep will take more time. After all, we're doing this in our free time too... :sweat_smile:

**Comment by AngryGami** [comment]
I'll see what I can collect related to what you've suggested. I only have one device which is meant to work in very narrow usecase therefore I don't need most of versatility you are describing that is related to audio formats and devices. So gaming and complex scenarios (with bluetooth headphones etc.) are not my priority.

**Comment by MarijnS95** [comment]
> I only have one device

I wasn't intending you to test all - rather, if you are able to test just the one you have that saves me quite some time, as _I_ "am" on testing and fixing "duty".



> I don't need most of versatility you are describing

It'd save me some time, but is perhaps better if I do all the structured testing - I have to validate the logs after all. Just let me know if specific things aren't working and I'll take a look, the rest has to wait for a bit longer then.

**Comment by AngryGami** [comment]
Ok. I've build from latest source I have access to. There is funny "whoop" sound during first boot of the device, though subsequent reboots are silent. 
Finally there is at least some sound from phone but behavior is quite strange and unstable. Here what I meant: https://youtu.be/GOfpiaKsO38 (when tweak call volume it appears and when tweaking with media volume it disappears again, though this is not the only situation when sound disappear, just one that I can reproduce reliably)
Logs from this session are [here](https://github.com/sonyxperiadev/bug_tracker/files/5051520/soundcheck.log). Though maybe you need some other logs, just tell me how to collect these and I'll do. I doubt this particular problem is related to codecs and therefore no need for `ffprobe`.

**Comment by MarijnS95** [comment]
> There is funny "whoop" sound during first boot of the device

Nice, that means the calibration did its job :)

Upon _very quick_ scrollthrough of the logs, did you revert https://github.com/sonyxperiadev/device-sony-pdx201/commit/f58e3ae0f49b99bc1117540321034e8aefb5bcab ?

**Comment by AngryGami** [comment]
No, should I? 
My usual sequence of actions when rebuilding is just do `repo sync`, then `repo_update.sh`, remove `out\target\product\pdx201`, select lunch option, build, and after build finishes - flash and test.

**Comment by MarijnS95** [comment]
> No, should I?
> My usual sequence of actions when rebuilding

In this specific case, yes. As [mentioned above](https://github.com/sonyxperiadev/bug_tracker/issues/617#issuecomment-671246659) audio is likely broken, reverting that commit being a likely temporary fix.

**Comment by AngryGami** [comment]
I've tested without this patch and basic sound related functions seems to work. I'll continue from this point then.
