### ISSUE TITLE
Xperia XA2 Ultra - Primary camera is not working

### ISSUE THREAD

**Issue by jerpelea** [sonyxperiadev/bug_tracker#95]
**Platform:** Nile
**Device:** XA2 XA2 Ultra
**Kernel version:** 4.4
**Android version:** 8.x

**Description**
Main camera does not start

**Symptoms**
Main camera does not start

**How to reproduce**
start camera app

**Comment by jerpelea** [comment]
[    4.470084] msm_cci_wait: 305 wait for queue: 0
[    4.470162] msm_cci_transfer_end: 558 failed rc -110
[    4.470254] msm_cci_data_queue: 815 failed rc -110
[    4.470306] msm_actuator_vcm2_init_focus:557 i2c_operation fail, rc = -110

**Comment by jerpelea** [comment]
https://github.com/sonyxperiadev/kernel/pull/1596

**Comment by wargreymon-opensrc** [comment]
Camera on XA2 Ultra is still not working. Is there going to be an update or have it been fixed yet???

**Comment by MarijnS95** [comment]
@wargreymon-opensrc Are you on Kernel 4.14?

If so:
https://github.com/sonyxperiadev/bug_tracker/issues/513

The camera has been fixed, and will be released in the upcoming V3 binary sources! :grin:

**Comment by wargreymon-opensrc** [comment]
It's 4.4.153-pref+

It still hangs, then primary camera and flashlight are dead.

在 2020年1月10日週五 下午8:31，MarijnS95 <notifications@github.com> 寫道：

**Comment by MarijnS95** [comment]
> It's 4.4.153-pref+

This  bug tracker is only for issues with the Sony Open Devices project, which has [its own kernel](github.com/sonyxperiadev/kernel).

For stock-based solutions please contact your ROM maintainer, and _at least_ provide them the logs.

**Comment by jerpelea** [comment]
next vendor release fixes camera

**Comment by mahdinahal** [comment]
Is there any solution available after all this time?
